
(()=>{
const D=window.UI_AR_DATA, app=document.querySelector('#app');
const norm=s=>(s||'').toLowerCase().normalize('NFD').replace(/[\u064B-\u065F\u0670]/g,'').replace(/[أإآ]/g,'ا').replace(/ى/g,'ي').replace(/ة/g,'ه').replace(/[^\p{L}\p{N}]+/gu,' ').trim();
const state={q:'',cat:'all',sort:'newest'};
const href=(p)=>'#'+p;
const nav=(active='elements')=>`<div class="topline">قاموس بصري عربي لعناصر الواجهة — المصطلح العربي + الاسم الإنجليزي + رمز التنفيذ</div><header><div class="shell nav"><a class="brand" href="#/">ما اسم هذا العنصر؟ <small>UI بالعربي</small></a><a class="${active==='elements'?'active':''}" href="#/">العناصر</a><a class="${active==='styles'?'active':''}" href="#/styles">الأنماط</a><a class="${active==='compare'?'active':''}" href="#/compare">المتشابهات</a><a class="${active==='translate'?'active':''}" href="#/translate">جدول الترجمة</a></div></header>`;
const footer=()=>`<footer class="footer"><div class="shell"><b>ما اسم هذا العنصر؟</b><div>قاموس بصري عربي مستقل لمصطلحات UI. الأسماء البرمجية تبقى كما تعتمدها المنصات والأطر.</div><div class="links"><a href="#/compare">العناصر المتشابهة</a><a href="#/methodology">المنهجية</a><a href="#/guide/appkit-swiftui">AppKit أم SwiftUI؟</a><a href="#/guide/swift-electron">Swift أم Electron؟</a><a href="#/support">دعم المشروع</a><a href="feed.xml">RSS</a></div></div></footer><div id="glossary" class="glossary"></div>`;
function genericDemo(e){
 const code=e.code.replace(/</g,'&lt;').replace(/>/g,'&gt;');
 return `<div class="demo-ui" aria-hidden="true"><span class="pill">${e.ar}</span><div class="line"></div><div class="line short"></div><code class="code">${code}</code></div>`;
}
function card(e){return `<a class="card" href="#/element/${e.slug}"><div class="demo">${genericDemo(e)}</div><div class="cardbody"><div class="meta">${e.new?'<span class="badge new">جديد</span>':''}<span class="badge">${e.category==='web'?'Web':'macOS'}</span></div><h3>${e.ar}</h3><div class="en">${e.en}</div><code class="code">${e.code.replace(/</g,'&lt;').replace(/>/g,'&gt;')}</code><p>${e.description}</p></div></a>`}
function searchMatches(e,q){if(!q)return true;const hay=norm([e.ar,e.en,e.code,e.description,...e.aliases].join(' '));return norm(q).split(' ').every(x=>hay.includes(x))}
function home(){
 document.title='ما اسم هذا العنصر؟ — قاموس UI بالعربي';
 const examples=['النقاط الصغيرة أسفل عرض الصور','الخلفية الداكنة خلف النافذة المنبثقة','النص الرمادي الذي يختفي عند الكتابة','الدائرة التي أسحبها لتغيير الصوت','النص الذي ينتهي بثلاث نقاط'];
 app.innerHTML=nav('elements')+`<main id="main" class="shell"><section class="hero"><div class="eyebrow">القاموس البصري لعناصر واجهة المستخدم</div><h1>ما اسم عنصر الواجهة هذا؟</h1><p>صف الشيء بطريقتك حتى لو لم تعرف المصطلح. ستحصل على الاسم العربي المهني، الاسم الإنجليزي المتداول، رمز التنفيذ، وPrompt جاهز لوكيل البرمجة.</p><div class="searchwrap"><input id="search" class="search" autocomplete="off" placeholder="مثال: الشيء الذي يظهر فوق الصفحة ويغمّق الخلفية…" value="${state.q.replace(/"/g,'&quot;')}" /></div><div class="examples">${examples.map(x=>`<button data-example="${x}">${x}</button>`).join('')}</div><p style="font-size:12px;margin-top:18px">انقر نقراً مزدوجاً على مصطلح محدد لعرض تعريف سريع.</p></section><section><div class="toolbar"><button class="chip ${state.cat==='all'?'active':''}" data-cat="all">الكل <b>81</b></button><button class="chip ${state.cat==='web'?'active':''}" data-cat="web">Web <b>49</b></button><button class="chip ${state.cat==='macos'?'active':''}" data-cat="macos">macOS <b>32</b></button><button class="chip ${state.sort==='newest'?'active':''}" data-sort="newest">الأحدث</button><button class="chip ${state.sort==='popular'?'active':''}" data-sort="popular">الأكثر شيوعاً</button><span id="count" class="count"></span></div><div id="cards" class="grid"></div></section></main>`+footer();
 const render=()=>{let list=D.entries.filter(e=>(state.cat==='all'||e.category===state.cat)&&searchMatches(e,state.q));list=[...list].sort((a,b)=>state.sort==='popular'?b.popularity-a.popularity:Number(b.new)-Number(a.new));document.querySelector('#cards').innerHTML=list.length?list.map(card).join(''):`<div class="emptysearch" style="grid-column:1/-1"><b>لا توجد نتيجة مطابقة.</b><br>جرّب وصف الشكل أو موضعه أو وظيفته بكلمات أبسط.</div>`;document.querySelector('#count').textContent=`${list.length} نتيجة`;};
 render();
 document.querySelector('#search').addEventListener('input',e=>{state.q=e.target.value;render()});
 document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{state.cat=b.dataset.cat;home()});
 document.querySelectorAll('[data-sort]').forEach(b=>b.onclick=()=>{state.sort=b.dataset.sort;home()});
 document.querySelectorAll('[data-example]').forEach(b=>b.onclick=()=>{state.q=b.dataset.example;home();document.querySelector('#search').focus()});
 bindGlossary();
}
function specimen(e){return `<div class="specimen"><div class="big"><div style="display:flex;justify-content:space-between;gap:10px;align-items:center"><b>${e.ar}</b><span class="badge">${e.category==='web'?'Web':'macOS'}</span></div><div style="margin-top:18px">${genericDemo(e)}</div><div style="color:#777;font-size:12px;margin-top:12px">هذا نموذج توضيحي أصلي للعنصر وليس لقطة من الموقع المرجعي.</div></div></div>`}
function detail(slug){const e=D.entries.find(x=>x.slug===slug);if(!e)return notFound();document.title=`${e.ar} — ${e.en}`;const rel=D.entries.filter(x=>x.slug!==e.slug&&(x.category===e.category)).slice(0,5);app.innerHTML=nav('elements')+`<main id="main" class="shell"><article class="detail"><div class="crumbs"><a href="#/">الفهرس</a><span>/</span><span>${e.category==='web'?'Web':'macOS'}</span></div><div class="actions"><button id="save">☆ حفظ</button><button id="share">مشاركة</button><button id="copyurl">نسخ رابط الصفحة</button></div>${specimen(e)}<h1>${e.ar}</h1><div class="en" style="font-size:16px">${e.en}</div><code class="code">${e.code.replace(/</g,'&lt;').replace(/>/g,'&gt;')}</code><p class="aka"><b>يُسمى أيضاً:</b> ${e.aliases.join('، ')}</p><p class="lead">${e.description}</p><section class="section"><h2>إذا كنت تسميه…</h2><p>${e.aliases.map(a=>`«${a}»`).join(' · ')} · «${e.description.split(' ').slice(0,7).join(' ')}…»</p><p><b>فالمصطلح الذي تبحث عنه هو: ${e.ar} — ${e.en}.</b></p></section><section class="section"><h2>التشريح — اسم كل جزء</h2><div class="anatomy">${e.anatomy.map((p,i)=>`<div class="part"><b>${i+1}. ${p.name}</b><p>${p.desc}</p></div>`).join('')}</div></section><section class="section"><h2>Prompt — جاهز لوكيل البرمجة</h2><div class="prompt"><button class="copybtn" data-copy="${encodeURIComponent(e.prompt)}">نسخ</button>${e.prompt}</div></section><section class="section"><h2>Debug Prompt — عند وجود مشكلة</h2><div class="prompt"><button class="copybtn" data-copy="${encodeURIComponent(e.debug)}">نسخ</button>${e.debug}</div></section><section class="section"><h2>في الكود</h2><table class="code-table"><tbody>${e.inCode.map(r=>`<tr><td>${r.stack}</td><td><code>${r.symbol.replace(/</g,'&lt;').replace(/>/g,'&gt;')}</code></td><td>${r.note}</td></tr>`).join('')}</tbody></table></section><section class="section"><h2>راجع أيضاً</h2><div class="related">${rel.map(r=>`<a href="#/element/${r.slug}">${r.ar}<br><span class="en">${r.en}</span></a>`).join('')}</div></section></article></main>`+footer();
 const key='saved-ui-ar', saved=new Set(JSON.parse(localStorage.getItem(key)||'[]'));const sb=document.querySelector('#save');const sync=()=>sb.textContent=saved.has(e.slug)?'★ محفوظ':'☆ حفظ';sync();sb.onclick=()=>{saved.has(e.slug)?saved.delete(e.slug):saved.add(e.slug);localStorage.setItem(key,JSON.stringify([...saved]));sync()};document.querySelector('#share').onclick=async()=>{const u=location.href;if(navigator.share){try{await navigator.share({title:e.ar,text:e.description,url:u})}catch{}}else navigator.clipboard?.writeText(u)};document.querySelector('#copyurl').onclick=()=>navigator.clipboard?.writeText(location.href);document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>navigator.clipboard?.writeText(decodeURIComponent(b.dataset.copy)));bindGlossary();}
function styles(){document.title='أنماط الواجهات — UI بالعربي';app.innerHTML=nav('styles')+`<main id="main" class="shell"><section class="hero"><div class="eyebrow">أطلس الأنماط البصرية</div><h1>ما اسم هذا الأسلوب؟</h1><p>تعرّف على الاسم الحقيقي للأسلوب، الإشارات التي تميّزه، وما الذي يفصله عن أقرب أسلوب مشابه.</p></section><div class="style-grid">${D.styles.map(s=>`<a class="style-card" href="#/style/${s.slug}"><div class="style-demo ${s.slug}">${s.en}</div><div class="meta"><span class="badge">${s.status}</span></div><h3>${s.ar}</h3><div class="en">${s.en}</div><p>${s.desc}</p><div class="signals">${s.signals.map(x=>`<span>${x}</span>`).join('')}</div></a>`).join('')}</div></main>`+footer();bindGlossary()}
function styleDetail(slug){const s=D.styles.find(x=>x.slug===slug);if(!s)return notFound();document.title=`${s.ar} — ${s.en}`;app.innerHTML=nav('styles')+`<main id="main" class="shell"><article class="detail"><div class="crumbs"><a href="#/styles">الأنماط</a><span>/</span><span>${s.en}</span></div><div class="specimen"><div class="style-demo ${s.slug}" style="width:min(650px,100%);height:260px;border-radius:24px">${s.ar}</div></div><h1>${s.ar}</h1><div class="en" style="font-size:16px">${s.en}</div><span class="badge">${s.status}</span><p class="lead">${s.desc}</p><section class="section"><h2>ما الذي يجعله هذا الأسلوب؟</h2><div class="anatomy">${s.signals.map((x,i)=>`<div class="part"><b>${i+1}. ${x}</b><p>إشارة بصرية أساسية تساعد على تمييز ${s.ar} من الأنماط القريبة.</p></div>`).join('')}</div></section><section class="section"><h2>Style Brief — جاهز للوكيل</h2><div class="prompt">طبّق أسلوب ${s.ar} (${s.en}). الإشارات الأساسية: ${s.signals.join('؛ ')}. حافظ على قابلية القراءة، تباين النص، حالات التركيز، وبدائل مناسبة عند تقليل الحركة أو الشفافية.</div></section><section class="section"><h2>غالباً يختلط مع</h2><p><b>${s.confused}</b> — افصل بينهما بحسب الإشارات الأساسية السابقة، لا بحسب اللون وحده.</p></section><section class="section"><h2>DNA الكامل للأسلوب</h2><div class="anatomy"><div class="part"><b>السطح والخامة</b><p>${s.signals[0]}</p></div><div class="part"><b>اللون والتباين</b><p>${s.signals[1]||s.signals[0]}</p></div><div class="part"><b>الهندسة والحدود</b><p>${s.signals[2]||'تتبع منطق الأسلوب دون زخرفة غير مرتبطة.'}</p></div><div class="part"><b>العمق والحركة</b><p>استخدمهما فقط بقدر يخدم هوية الأسلوب ولا يضر الإتاحة.</p></div></div></section><section class="section"><h2>في الكود — نقطة بداية</h2><div class="prompt">${s.code}</div></section><section class="section"><h2>الإتاحة وسوء الاستخدام</h2><ul><li>اختبر تباين النص في أسوأ حالة للخلفية.</li><li>لا تجعل الشكل البصري يحل محل الدلالة أو حالات التركيز.</li><li>احترم prefers-reduced-motion ويفضل توفير بديل للشفافية الثقيلة عند الحاجة.</li></ul></section></article></main>`+footer();bindGlossary()}
function compare(){document.title='العناصر التي يكثر الخلط بينها';app.innerHTML=nav('compare')+`<main id="main" class="shell"><section class="hero"><div class="eyebrow">Commonly Confused</div><h1>عناصر تبدو متشابهة، لكن الفرق حاسم.</h1><p>كل مقارنة تبدأ بالفرق الذي يمكنك ملاحظته مباشرة في البكسلات أو السلوك.</p></section><div class="compare-list">${D.comparisons.map(c=>`<article class="compare"><h3>${c.title}</h3><p>${c.answer}</p></article>`).join('')}</div></main>`+footer();bindGlossary()}
function translate(){document.title='جدول الترجمة — AppKit وSwiftUI';app.innerHTML=nav('translate')+`<main id="main" class="shell"><section class="hero"><div class="eyebrow">الاسم البصري · AppKit · SwiftUI</div><h1>جدول الترجمة</h1><p>ابحث عن الشيء الذي تراه، ثم خذ الاسم المناسب للتقنية التي يستخدمها مشروع macOS.</p><div class="searchwrap"><input id="tsearch" class="search" placeholder="جرّب: segmented أو NSPopUpButton أو تنبيه" /></div></section><div id="ttable"></div></main>`+footer();const draw=()=>{const q=norm(document.querySelector('#tsearch').value);const rows=D.translations.filter(r=>!q||norm(Object.values(r).join(' ')).includes(q));document.querySelector('#ttable').innerHTML=`<table class="translation"><thead><tr><th>العنصر</th><th>AppKit</th><th>SwiftUI</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.thing}</td><td><code>${r.appkit}</code></td><td><code>${r.swiftui}</code></td></tr>`).join('')}</tbody></table><p style="color:var(--muted);font-size:12px">${rows.length} من 63 ترجمة</p>`};draw();document.querySelector('#tsearch').oninput=draw;bindGlossary()}
function guide(kind){let title,body;if(kind==='appkit-swiftui'){title='AppKit أم SwiftUI؟';body=`<p class="lead">العنصر نفسه على شاشة Mac قد يملك اسمين صحيحين لأن AppKit وSwiftUI واجهتان برمجيتان مختلفتان.</p><h2>ثلاث قواعد</h2><ol><li><b>طابق المشروع:</b> إذا كانت الواجهات SwiftUI فاستخدم أسماء SwiftUI؛ إذا كانت NS* فاستخدم AppKit.</li><li><b>في المشاريع المختلطة، سمِّ الطبقة:</b> قل “SwiftUI view داخل NSWindow” مثلاً.</li><li><b>عند الشك اذكر الاسمين:</b> مثال MenuBarExtra / NSStatusItem.</li></ol><h2>لا تخلطها مع</h2><div class="callout">UIKit للـiPhone وiPad، وMac Catalyst لتطبيقات iPad على Mac، وElectron واجهة ويب داخل تطبيق سطح مكتب.</div><p><a class="chip active" href="#/translate">افتح جدول الترجمة الكامل (63 مصطلحاً)</a></p>`}else{title='Swift أم Electron؟';body=`<p class="lead">هذا قرار مبكر يحدد مفردات الواجهة. Swift يستخدم تقنيات Apple الأصلية، بينما Electron يشغّل واجهة ويب داخل Chromium مع Node.js.</p><h2>الفرق العملي</h2><table class="translation"><tr><th>Swift</th><th>Electron</th></tr><tr><td>واجهة Mac أصلية وAppKit/SwiftUI</td><td>HTML/CSS/JS داخل BrowserWindow</td></tr><tr><td>مصطلحات NSWindow وMenuBarExtra</td><td>مصطلحات DOM وCSS وTray</td></tr><tr><td>أفضل لتجربة Mac أصلية</td><td>مناسب لمشاركة كود ويب عبر المنصات</td></tr></table><h2>قاعدة عملية</h2><p>اختر العالم التقني أولاً ثم استخدم مصطلحاته الدقيقة في الـPrompt، ولا تخلط API من عالم بآخر.</p>`}document.title=title;app.innerHTML=nav('')+`<main id="main" class="shell"><article class="guide"><div class="crumbs"><a href="#/">الفهرس</a><span>/</span><span>دليل</span></div><h1>${title}</h1>${body}</article></main>`+footer();bindGlossary()}
function methodology(){document.title='المنهجية';app.innerHTML=nav('')+`<main id="main" class="shell"><article class="guide"><div class="eyebrow">شاهد · تحقق · سمِّ</div><h1>المنهجية</h1><p class="lead">نبدأ من الشيء المرئي الذي يصعب وصفه، ثم نثبت اسمه من توثيق المنصة والدلالة البرمجية ومعايير الإتاحة قبل إدراجه.</p><h2>كيف يدخل المصطلح؟</h2><ol><li><b>ابدأ بالبكسلات:</b> يجب أن يشير الاسم إلى شيء يراه المستخدم فعلًا.</li><li><b>تحقق من المنصة:</b> راجع اسم النمط في دليل التصميم، ورمز API في التوثيق، والدور الدلالي عند وجوده.</li><li><b>اجعل الفرق مرئيًا:</b> المثال والتشريح يجب أن يفرقا العنصر عن أقرب بدائل له.</li></ol><h2>المصادر المرجعية</h2><div class="anatomy"><div class="part"><b>Apple</b><p>Human Interface Guidelines وDeveloper Documentation لأسماء AppKit وSwiftUI وUIKit.</p></div><div class="part"><b>الويب المتاح</b><p>WAI-ARIA وARIA APG وWCAG للدور والسلوك والوصول.</p></div><div class="part"><b>منصة الويب</b><p>WHATWG HTML وMDN للأسماء الدلالية وواجهات المتصفح.</p></div><div class="part"><b>البحث الحقيقي</b><p>عبارات المستخدمين تساعد على العثور، لكنها لا تستبدل الاسم القياسي.</p></div></div><h2>عندما تختلف الأسماء</h2><p>نُبقي المنصة ملاصقة للمصطلح ونظهر الاسم البديل المفيد بدل الادعاء بوجود اسم عالمي واحد.</p></article></main>`+footer();bindGlossary()}
function support(){document.title='دعم المشروع';app.innerHTML=nav('')+`<main id="main" class="shell"><article class="guide"><div class="eyebrow">Support</div><h1>دعم القاموس العربي</h1><p class="lead">هذه الصفحة مهيأة لمساحة دعم أو رعاية مستقبلية من دون ادعاء أرقام زيارات أو رعاة غير موجودين.</p><div class="callout"><b>مبدأ ثابت:</b> أي دعم مالي لا يغيّر تعريفات العناصر، ترتيب نتائج البحث، أو المنهجية التحريرية.</div><h2>ما الذي يمكن عرضه هنا؟</h2><ul><li>اسم الداعم ووصف قصير ورابط.</li><li>سياسة واضحة بعدم إضافة تتبع إعلاني خفي.</li><li>وسيلة تواصل يحددها مالك المشروع لاحقًا.</li></ul></article></main>`+footer();bindGlossary()}
function notFound(){app.innerHTML=nav('')+`<main id="main" class="shell"><section class="hero"><h1>الصفحة غير موجودة</h1><p><a class="chip active" href="#/">العودة إلى الفهرس</a></p></section></main>`+footer()}
function bindGlossary(){const box=document.querySelector('#glossary');document.addEventListener('dblclick',ev=>{const w=(getSelection()?.toString()||'').trim();if(!w||!box)return;const key=Object.keys(D.glossary).find(k=>norm(k)===norm(w));box.textContent=key?D.glossary[key]:`«${w}»: لا يوجد تعريف سريع محفوظ لهذا المصطلح بعد.`;box.style.display='block';box.style.left=Math.max(10,Math.min(innerWidth-340,ev.clientX))+'px';box.style.top=Math.max(80,ev.clientY+14)+'px';setTimeout(()=>box.style.display='none',4500)},{once:true})}
function router(){scrollTo(0,0);const p=location.hash.slice(1)||'/';const seg=p.split('/').filter(Boolean);if(!seg.length)return home();if(seg[0]==='element')return detail(seg[1]);if(seg[0]==='styles'&&seg.length===1)return styles();if(seg[0]==='style')return styleDetail(seg[1]);if(seg[0]==='compare')return compare();if(seg[0]==='translate')return translate();if(seg[0]==='methodology')return methodology();if(seg[0]==='guide')return guide(seg[1]);if(seg[0]==='support')return support();return notFound()}
addEventListener('hashchange',router);router();
})();