const categories=[
{id:'buttons',ar:'الأزرار',en:'Buttons',icon:'◉',desc:'أزرار أساسية وتفاعلية',styles:['All','Minimal','Neon','Outline','Animated']},
{id:'hover',ar:'تأثيرات Hover',en:'Hover Effects',icon:'↗',desc:'حركات واستجابات المؤشر',styles:['All','Glow','Border','Fill','Scale']},
{id:'cards',ar:'البطاقات',en:'Cards',icon:'▣',desc:'بطاقات محتوى ولوحات تحكم',styles:['All','Minimal','Glass','Dashboard','Profile']},
{id:'inputs',ar:'الحقول والنماذج',en:'Inputs & Forms',icon:'⌨',desc:'حقول ونماذج إدخال',styles:['All','Minimal','Search','Validation','Soft']},
{id:'nav',ar:'التنقل',en:'Navigation Bars',icon:'☷',desc:'قوائم تنقل وشريط علوي',styles:['All','Minimal','Pill','Floating','Dark']},
{id:'modals',ar:'النوافذ',en:'Modals & Popups',icon:'▢',desc:'حوارات وتنبيهات منبثقة',styles:['All','Confirm','Alert','Glass','Sheet']},
{id:'menus',ar:'القوائم',en:'Dropdowns & Menus',icon:'⌄',desc:'قوائم واختيارات سياقية',styles:['All','Actions','Context','Select','Dropdown']},
{id:'loaders',ar:'التحميل والتقدم',en:'Loaders & Progress',icon:'◌',desc:'مؤشرات انتظار وتقدم',styles:['All','Spinner','Progress']},
{id:'tabs',ar:'التبويبات والأكورديون',en:'Tabs & Accordions',icon:'≡',desc:'تنظيم المحتوى التفاعلي',styles:['All','Tabs','Pill','Underline','Accordion']},
{id:'motion',ar:'الحركات الدقيقة',en:'Micro-interactions',icon:'✦',desc:'حركات صغيرة تضيف حياة',styles:['All','Scale','Pulse','Rotate','Magnetic']}
];
const raw=[
['BTN-001','buttons','Solid Core','Minimal',['button','minimal','black'],`<button class="demo-btn primary">ابدأ الآن</button>`],
['BTN-002','buttons','Electric Glow','Neon',['button','glow','blue','hover'],`<button class="demo-btn glow">استكشف المكتبة</button>`],
['BTN-003','buttons','Clean Outline','Outline',['button','outline','minimal'],`<button class="demo-btn outline">عرض التفاصيل</button>`],
['BTN-004','buttons','Liquid Fill','Animated',['button','fill','liquid','hover'],`<button class="demo-btn liquid"><span>مرّر المؤشر</span></button>`],
['HOV-001','hover','Glow Lift','Glow',['hover','glow','lift','blue'],`<button class="demo-btn glow">Glow Lift</button>`],
['HOV-002','hover','Invert Border','Border',['hover','border','invert'],`<button class="demo-btn outline">Invert Border</button>`],
['HOV-003','hover','Liquid Sweep','Fill',['hover','fill','sweep'],`<button class="demo-btn liquid"><span>Liquid Sweep</span></button>`],
['HOV-004','hover','Micro Scale','Scale',['hover','scale','micro'],`<div class="micro">↗</div>`],
['CRD-001','cards','Content Card','Minimal',['card','content','minimal'],`<article class="demo-card"><div class="thumb"></div><h4>عنوان البطاقة</h4><p>وصف مختصر يوضح محتوى البطاقة بشكل واضح.</p></article>`],
['CRD-002','cards','Glass Card','Glass',['card','glass','blur'],`<article class="demo-card" style="background:rgba(255,255,255,.62);backdrop-filter:blur(10px)"><div class="thumb"></div><h4>Glass Surface</h4><p>بطاقة زجاجية خفيفة لمناطق المحتوى البارزة.</p></article>`],
['CRD-003','cards','KPI Card','Dashboard',['card','dashboard','kpi'],`<article class="demo-card"><small style="color:#7a8090;font-size:7px">إجمالي الزيارات</small><h4 style="font-size:24px;margin:6px 0">12,480</h4><p>+18.4% مقارنة بالشهر السابق</p></article>`],
['CRD-004','cards','Profile Card','Profile',['card','profile','user'],`<article class="demo-card" style="text-align:center"><div style="width:46px;height:46px;border-radius:50%;background:#e9edff;margin:auto auto 9px"></div><h4>مستخدم تجريبي</h4><p>UI Designer · Gaza</p></article>`],
['INP-001','inputs','Focus Ring','Minimal',['input','focus','form'],`<input class="demo-input" placeholder="اكتب هنا...">`],
['INP-002','inputs','Search Field','Search',['input','search','field'],`<input class="demo-input" placeholder="ابحث في المكتبة...">`],
['INP-003','inputs','Email Field','Validation',['input','email','validation'],`<input class="demo-input" type="email" value="mohanad@example.com">`],
['INP-004','inputs','Soft Input','Soft',['input','soft','rounded'],`<input class="demo-input" style="border:0;background:#f0f2f7" placeholder="اسم المشروع">`],
['NAV-001','nav','Compact Nav','Minimal',['nav','navbar','minimal'],`<nav class="demo-nav"><b>Brand</b><span class="active">الرئيسية</span><span>المكتبة</span><span>حول</span></nav>`],
['NAV-002','nav','Pill Navigation','Pill',['nav','pill','rounded'],`<nav class="demo-nav" style="border-radius:999px"><b>M</b><span>Home</span><span class="active">Library</span><span>Labs</span></nav>`],
['NAV-003','nav','Floating Bar','Floating',['nav','floating','bar'],`<nav class="demo-nav" style="box-shadow:0 16px 35px rgba(30,38,62,.14)"><b>UI</b><span>Components</span><span class="active">Top 10</span></nav>`],
['NAV-004','nav','Dark Nav','Dark',['nav','dark','contrast'],`<nav class="demo-nav" style="background:#111;color:#fff;border-color:#111"><b>Library</b><span style="color:#aaa">Browse</span><span class="active" style="background:#fff;color:#111">Saved</span></nav>`],
['MOD-001','modals','Confirm Modal','Confirm',['modal','confirm','dialog'],`<div class="demo-modal"><b>تأكيد الإجراء</b><p>هل تريد تنفيذ هذا الإجراء الآن؟</p><div class="actions"><button>تأكيد</button><button>إلغاء</button></div></div>`],
['MOD-002','modals','Info Dialog','Alert',['modal','info','alert'],`<div class="demo-modal"><b>تم الحفظ</b><p>تمت إضافة العنصر إلى مجموعتك بنجاح.</p><div class="actions"><button>حسنًا</button></div></div>`],
['MOD-003','modals','Glass Dialog','Glass',['modal','glass','blur'],`<div class="demo-modal" style="background:rgba(255,255,255,.68);backdrop-filter:blur(12px)"><b>Glass Dialog</b><p>نموذج خفيف لواجهات مستقبلية نظيفة.</p></div>`],
['MOD-004','modals','Action Sheet','Sheet',['modal','sheet','actions'],`<div class="demo-modal"><b>خيارات العنصر</b><p>نسخ الكود أو إضافته للمفضلة.</p><div class="actions"><button>نسخ</button><button>مفضلة</button></div></div>`],
['MNU-001','menus','Action Menu','Actions',['menu','actions','dropdown'],`<div class="demo-menu"><div>نسخ الكود</div><div>إضافة للمفضلة</div><div>فتح في التركيز</div></div>`],
['MNU-002','menus','Context Menu','Context',['menu','context','popup'],`<div class="demo-menu"><div>فتح</div><div>تكرار</div><div style="color:#c64747">حذف</div></div>`],
['MNU-003','menus','Select Menu','Select',['menu','select','options'],`<div class="demo-menu"><div>Minimal ✓</div><div>Glass</div><div>Neon</div></div>`],
['MNU-004','menus','Dropdown','Dropdown',['menu','dropdown','list'],`<div class="demo-menu"><div>HTML / CSS</div><div>React</div><div>Tailwind</div></div>`],
['LOD-001','loaders','Classic Spinner','Spinner',['loader','spinner','loading'],`<div class="loader"></div>`],
['LOD-002','loaders','Progress Line','Progress',['progress','bar','loading'],`<div class="progress"><span></span></div>`],
['LOD-003','loaders','Soft Spinner','Spinner',['loader','soft','spinner'],`<div class="loader" style="border-top-color:#111;border-width:3px;width:32px;height:32px"></div>`],
['LOD-004','loaders','Gradient Progress','Progress',['progress','gradient','bar'],`<div class="progress"><span style="background:linear-gradient(90deg,#3559e8,#8a5cff)"></span></div>`],
['TAB-001','tabs','Soft Tabs','Tabs',['tabs','soft','switch'],`<div class="demo-tabs"><span class="active">HTML</span><span>React</span><span>Tailwind</span></div>`],
['TAB-002','tabs','Dark Tabs','Pill',['tabs','dark','pill'],`<div class="demo-tabs" style="background:#111;color:#aaa"><span>Preview</span><span class="active">Code</span></div>`],
['TAB-003','tabs','Underline Tabs','Underline',['tabs','underline','minimal'],`<div style="display:flex;gap:18px;font-size:9px"><span style="border-bottom:2px solid #3559e8;padding:8px">Overview</span><span style="padding:8px;color:#777">Details</span></div>`],
['TAB-004','tabs','Accordion Row','Accordion',['accordion','row','collapse'],`<div class="demo-menu" style="width:230px"><div style="display:flex;justify-content:space-between"><b>قسم قابل للفتح</b><span>⌄</span></div></div>`],
['MOT-001','motion','Morph Hover','Scale',['motion','hover','scale'],`<div class="micro">+</div>`],
['MOT-002','motion','Pulse Dot','Pulse',['motion','pulse','status'],`<div style="width:18px;height:18px;border-radius:50%;background:#3559e8;box-shadow:0 0 0 0 rgba(53,89,232,.4);animation:pulse 1.6s infinite"></div>`],
['MOT-003','motion','Rotate Tile','Rotate',['motion','rotate','hover'],`<div class="micro" style="background:#3559e8">↻</div>`],
['MOT-004','motion','Magnetic Hint','Magnetic',['motion','magnetic','button'],`<button class="demo-btn primary">Magnetic ↗</button>`]
];
const samples=raw.map(([id,category,name,style,tags,html])=>({id,category,name,style,tags,html}));