const librarySources = [
  {
    id: "library-original",
    name: "Library- Original",
    url: "https://github.com/mmashharawi2021-cell/Library-",
    type: "internal-original",
    technology: "Original implementation inside Library-",
    license: "Project-owned source",
    extracted: ["original components","original interactions","local utility patterns"],
    usedBy: []
  },
  {
    id: "jitter-ui",
    name: "Jitter UI Animation Templates",
    url: "https://jitter.video/templates/ui-elements/",
    type: "visual-reference",
    technology: "Motion design reference",
    license: "Reference only; original web implementations are authored in Library-",
    extracted: ["buttons","toggles","loaders","progress","notifications","navigation","search","glass","micro-interactions"],
    usedBy: ["FXT-001","FXT-002","FXT-003","FXB-001","FXB-002","FXI-001"]
  },
  {
    id: "jitter-text",
    name: "Jitter Text Animation Templates",
    url: "https://jitter.video/templates/text/",
    type: "visual-reference",
    technology: "Motion typography reference",
    license: "Reference only; no Jitter template files copied",
    extracted: ["text reveal","stretch","scramble","morph","blur","glitch","loop typography"],
    usedBy: ["TXT-001","TXT-002","TXT-003","TXT-004"]
  },
  {
    id: "jitter-buttons",
    name: "Jitter Button Animation Templates",
    url: "https://jitter.video/templates/buttons/",
    type: "visual-reference",
    technology: "Interaction motion reference",
    license: "Reference only; original CSS/SVG implementation",
    extracted: ["glow","trace","split action","liquid glass","toggle","hover"],
    usedBy: ["BTN-018","BTN-019"]
  },
  {
    id: "dev-reui-2025",
    name: "DEV.to — ReUI component expansion",
    url: "https://dev.to/keenthemes/reui-v1016-just-shipped-our-biggest-update-since-launch-17l4",
    type: "discovery-article",
    technology: "React + TypeScript + Tailwind + Motion",
    license: "Article is reference only",
    extracted: ["stepper","file upload","tree","badge","marquee","text reveal","gradient background","grid background"],
    usedBy: ["INP-016","NAV-016","FXT-004","FXB-001"]
  },
  {
    id: "reui-official",
    name: "ReUI",
    url: "https://github.com/keenthemes/reui",
    type: "official-open-source",
    technology: "React + TypeScript + Tailwind",
    license: "MIT",
    extracted: ["production component patterns","accessibility","copy-and-own architecture"],
    usedBy: ["INP-016","NAV-016"]
  },
  {
    id: "motion-official",
    name: "Motion",
    url: "https://motion.dev/",
    type: "official-library",
    technology: "JavaScript + React animation",
    license: "MIT",
    extracted: ["entry/exit","gestures","scroll","layout transitions","stagger"],
    usedBy: ["FXT-001","FXS-001","FXS-002"]
  },
  {
    id: "dev-motion-guide-2026",
    name: "DEV.to — Motion React Animations Guide",
    url: "https://dev.to/stacknotice/framer-motion-motion-react-animations-complete-guide-2026-3e7l",
    type: "discovery-article",
    technology: "Motion + React",
    license: "Article is reference only",
    extracted: ["exit animation","shared layout","scroll effects","stagger","gestures"],
    usedBy: ["FXS-001","FXS-002"]
  },
  {
    id: "anime-official",
    name: "Anime.js",
    url: "https://animejs.com/",
    type: "official-library",
    technology: "JavaScript animation",
    license: "MIT",
    extracted: ["stagger","SVG","DOM transforms","loop","alternate"],
    usedBy: ["TXT-003","SVG-001"]
  },
  {
    id: "three-official",
    name: "Three.js",
    url: "https://github.com/mrdoob/three.js",
    type: "official-library",
    technology: "WebGL / 3D",
    license: "MIT",
    extracted: ["3D scenes","WebGL","interactive transforms"],
    usedBy: []
  },
  {
    id: "r3f-official",
    name: "React Three Fiber",
    url: "https://github.com/pmndrs/react-three-fiber",
    type: "official-library",
    technology: "React renderer for Three.js",
    license: "MIT",
    extracted: ["React 3D scene patterns","interactive 3D"],
    usedBy: []
  },
  {
    id: "dev-gsap-mask",
    name: "DEV.to — React + GSAP SVG mask / parallax pattern",
    url: "https://dev.to/er-raj-aryan/i-recreated-a-cinematic-gta-vi-website-clone-with-react-tailwind-gsap-3edc",
    type: "discovery-article",
    technology: "React + GSAP + SVG masking",
    license: "Article is reference only; no source code copied",
    extracted: ["SVG mask reveal","layered parallax","timeline sequencing"],
    usedBy: ["IMG-001","FXS-002"]
  },
  {
    "id": "dev-shadcn-2026",
    "name": "DEV.to — Shadcn UI in 2026",
    "url": "https://dev.to/whoffagents/shadcn-ui-in-2026-the-component-library-that-changed-how-we-build-uis-296o",
    "type": "discovery-article",
    "technology": "React + TypeScript + Tailwind",
    "license": "Article reference only",
    "extracted": [
      "button",
      "dialog",
      "dropdown",
      "copy-and-own",
      "accessible primitives"
    ],
    "usedBy": []
  },
  {
    "id": "shadcn-official",
    "name": "shadcn/ui",
    "url": "https://github.com/shadcn-ui/ui",
    "type": "official-open-source",
    "technology": "React + TypeScript + Tailwind + Radix/Base UI",
    "license": "MIT",
    "extracted": [
      "accordion",
      "alert-dialog",
      "avatar",
      "breadcrumb",
      "calendar",
      "carousel",
      "checkbox",
      "collapsible",
      "combobox",
      "command",
      "context-menu",
      "data-table",
      "date-picker",
      "drawer",
      "dropdown-menu",
      "hover-card",
      "input-otp",
      "menubar",
      "navigation-menu",
      "pagination",
      "popover",
      "progress",
      "radio-group",
      "resizable",
      "scroll-area",
      "separator",
      "sheet",
      "sidebar",
      "slider",
      "sonner",
      "switch",
      "table",
      "tabs",
      "textarea",
      "toggle",
      "toggle-group",
      "tooltip"
    ],
    "usedBy": []
  },
  {
    "id": "dev-anex-ui",
    "name": "DEV.to — Accessible React Component Library",
    "url": "https://dev.to/anex_ui/i-built-an-accessible-react-component-library-from-scratch-heres-what-i-learned-4lng",
    "type": "discovery-article",
    "technology": "React 19 + TypeScript + Tailwind + CSS Modules",
    "license": "Article reference only",
    "extracted": [
      "container",
      "stack",
      "grid",
      "divider",
      "alert",
      "badge",
      "table",
      "banner",
      "timeline",
      "number-input",
      "form-field"
    ],
    "usedBy": []
  },
  {
    "id": "dev-shadcn-collections",
    "name": "DEV.to — Curated shadcn-like React Collections",
    "url": "https://dev.to/keitam83/a-curated-list-of-shadcnui-like-react-component-collections-44pa",
    "type": "discovery-article",
    "technology": "React + Tailwind + Motion",
    "license": "Article reference only",
    "extracted": [
      "Magic UI",
      "Aceternity UI",
      "Motion Primitives"
    ],
    "usedBy": []
  },
  {
    "id": "magicui-official",
    "name": "Magic UI",
    "url": "https://github.com/magicuidesign/magicui",
    "type": "official-open-source",
    "technology": "React + TypeScript + Tailwind + Motion",
    "license": "MIT",
    "extracted": [
      "marquee",
      "animated-list",
      "border-beam",
      "shimmer-button",
      "number-ticker",
      "dock",
      "particles",
      "meteors",
      "ripple",
      "dot-pattern",
      "grid-pattern",
      "typing-animation",
      "blur-fade",
      "word-rotate",
      "hyper-text",
      "shine-border",
      "sparkles-text"
    ],
    "usedBy": []
  },
  {
    "id": "motion-primitives-official",
    "name": "Motion Primitives",
    "url": "https://github.com/ibelick/motion-primitives",
    "type": "official-open-source",
    "technology": "React + Tailwind + Motion",
    "license": "MIT",
    "extracted": [
      "animated-dialog",
      "animated-tabs",
      "text-effect",
      "text-loop",
      "text-morph",
      "cursor",
      "dock",
      "carousel",
      "accordion",
      "popover",
      "toolbar"
    ],
    "usedBy": []
  },
  {
    "id": "dev-tailgrids-2026",
    "name": "DEV.to — Tailgrids 3.0",
    "url": "https://dev.to/tailwindcss/tailgrids-react-ui-component-library-4k1c",
    "type": "discovery-article",
    "technology": "React + Tailwind",
    "license": "Reference only; TailGrids commercial license restricts redistribution/UI-builder use",
    "extracted": [
      "UI taxonomy",
      "blocks",
      "dashboards",
      "forms",
      "navbars",
      "footers",
      "alerts",
      "dropdowns"
    ],
    "usedBy": []
  },
  {
    id: "jitter-all-2026",
    name: "Jitter — All Templates 2026",
    url: "https://jitter.video/templates/all/",
    type: "official-template-gallery",
    technology: "Motion design reference",
    license: "Jitter-owned templates may be remixed/transformed; third-party/community branded assets are excluded unless terms are clear",
    extracted: ["UI elements","buttons","text","backgrounds","charts","icons","websites","devices","galleries","progress","loaders","transitions"],
    usedBy: []
  },
  {
    id: "dev-tailwind-libraries-2026",
    name: "DEV.to — Top Free Tailwind Component Libraries 2026",
    url: "https://dev.to/chnkc41/top-5-free-tailwind-component-libraries-in-2026-49f9",
    type: "discovery-article",
    technology: "Tailwind CSS ecosystem",
    license: "Article reference only",
    extracted: ["Ninna UI","daisyUI","shadcn/ui","Flowbite","Preline UI"],
    usedBy: []
  },
  {
    id: "daisyui-official",
    name: "daisyUI",
    url: "https://daisyui.com/components/",
    type: "official-component-catalog",
    technology: "Tailwind CSS plugin",
    license: "MIT",
    extracted: ["68 named component types"],
    usedBy: []
  },
  {
    id: "preline-official",
    name: "Preline UI",
    url: "https://preline.co/docs/components.html",
    type: "official-component-catalog",
    technology: "Tailwind CSS + JavaScript",
    license: "MIT + Preline UI Fair Use; Library- uses original reimplementations and attribution only",
    extracted: ["layout","base components","navigation","forms","overlays","tables","plugin patterns"],
    usedBy: []
  },
  {
    id: "flowbite-official",
    name: "Flowbite React",
    url: "https://flowbite-react.com/",
    type: "official-component-catalog",
    technology: "React + Tailwind CSS",
    license: "MIT",
    extracted: ["accordion","alert","avatar","banner","badge","breadcrumb","button","card","carousel","datepicker","dropdown","footer","forms","list-group","modal","navbar","pagination","progress","rating","sidebar","spinner","table","tabs","tooltip","timeline","toast"],
    usedBy: []
  },
  {
    id: "ninna-official",
    name: "Ninna UI",
    url: "https://github.com/ninna-ui/ninna-ui",
    type: "official-component-catalog",
    technology: "React 19 + TypeScript + Tailwind CSS v4",
    license: "MIT",
    extracted: ["primitives","feedback","forms","layout","overlays","navigation","data display","code block"],
    usedBy: []
  },
  {
    id: "dev-animated-ui-libraries",
    name: "DEV.to — Top Animated UI Component Libraries for React",
    url: "https://dev.to/codedthemes/top-animated-ui-component-libraries-for-react-1383",
    type: "discovery-article",
    technology: "React animation ecosystem",
    license: "Article reference only",
    extracted: ["Magic UI","Animate UI","Origin UI","HeroUI","React Bits"],
    usedBy: []
  },
  {
    id: "aceternity-reference",
    name: "Aceternity UI",
    url: "https://ui.aceternity.com/components",
    type: "official-component-gallery",
    technology: "React + Tailwind CSS + Motion",
    license: "Reference-only intake; Library- uses original reimplementations rather than redistributed source",
    extracted: ["motion-first marketing components","image effects","backgrounds","hero interactions"],
    usedBy: []
  },
  {
    id: "reactbits-reference",
    name: "React Bits",
    url: "https://github.com/DavidHDev/react-bits",
    type: "official-component-gallery",
    technology: "React + CSS/Tailwind + animation",
    license: "MIT + Commons Clause; source code is not redistributed in Library-",
    extracted: ["text animations","background effects","3D","interactive components"],
    usedBy: []
  },
  {
    id: "animateui-reference",
    name: "Animate UI",
    url: "https://github.com/imskyleen/animate-ui",
    type: "official-component-gallery",
    technology: "React + TypeScript + Tailwind + Motion",
    license: "MIT + Commons Clause condition; Library- uses original reimplementations only",
    extracted: ["animated primitives","dialogs","buttons","tabs","accordions","disclosure patterns"],
    usedBy: []
  },
  {
    id: "originui-official",
    name: "Origin UI",
    url: "https://github.com/shadcn/originui",
    type: "official-component-gallery",
    technology: "React + Tailwind CSS",
    license: "MIT",
    extracted: ["application UI","forms","inputs","buttons","navigation","tables","overlays"],
    usedBy: []
  },
  {
    id: "magicui-official",
    name: "Magic UI",
    url: "https://github.com/magicuidesign/magicui",
    type: "official-open-source",
    technology: "React + TypeScript + Tailwind + Motion",
    license: "MIT",
    extracted: ["marquee","animated list","border beam","shimmer button","number ticker","dock","particles","meteors","ripple","patterns","typing","blur fade","word rotate","hyper text","shine border","sparkles"],
    usedBy: []
  },
  {
    id: "motion-primitives-official",
    name: "Motion Primitives",
    url: "https://github.com/ibelick/motion-primitives",
    type: "official-open-source",
    technology: "React + Tailwind + Motion",
    license: "MIT",
    extracted: ["animated dialog","tabs","text effects","text loop","text morph","cursor","dock","carousel","accordion","popover","toolbar"],
    usedBy: []
  },
  {
    id: "dev-anex-ui",
    name: "DEV.to — Accessible React Component Library",
    url: "https://dev.to/anex_ui/i-built-an-accessible-react-component-library-from-scratch-heres-what-i-learned-4lng",
    type: "discovery-article",
    technology: "React + TypeScript + Tailwind",
    license: "Article reference only",
    extracted: ["layout primitives","feedback","forms","data display"],
    usedBy: []
  },
  {
    id: "shadcn-official",
    name: "shadcn/ui",
    url: "https://github.com/shadcn-ui/ui",
    type: "official-open-source",
    technology: "React + TypeScript + Tailwind",
    license: "MIT",
    extracted: ["accessible application primitives","forms","navigation","overlays","data display"],
    usedBy: []
  },
];

window.librarySources = librarySources;
