/* Search normalization, ranking, filtering and suggestions. */
const synonyms={'زر':'button','ازرار':'button','أزرار':'button','button':'button','buttons':'button','بطاقة':'card','بطاقات':'card','كرت':'card','card':'card','cards':'card','حقل':'input','ادخال':'input','إدخال':'input','input':'input','نموذج':'form','نماذج':'form','form':'form','قائمة':'menu','قوائم':'menu','menu':'menu','dropdown':'menu','تنقل':'nav','هيدر':'nav','navbar':'nav','navigation':'nav','nav':'nav','تحميل':'loader','loader':'loader','تقدم':'progress','progress':'progress','نافذة':'modal','منبثقة':'modal','modal':'modal','تبويب':'tabs','tabs':'tabs','اكورديون':'accordion','أكورديون':'accordion','accordion':'accordion','حركة':'animated','متحرك':'animated','متحركة':'animated','animation':'animated','animated':'animated','انيميشن':'animated','هوفر':'hover','hover':'hover','مرور':'hover','المؤشر':'hover','أسود':'dark','اسود':'dark','داكن':'dark','dark':'dark','أزرق':'blue','ازرق':'blue','blue':'blue','زجاجي':'glass','زجاج':'glass','شفاف':'glass','glass':'glass','blur':'glass','نيون':'neon','neon':'neon','توهج':'glow','متوهج':'glow','glow':'glow','بسيط':'minimal','نظيف':'minimal','minimal':'minimal','لوحة':'dashboard','لوحه':'dashboard','داشبورد':'dashboard','dashboard':'dashboard','kpi':'dashboard','متدرج':'gradient','gradient':'gradient','بحث':'search','search':'search','موبايل':'mobile','هاتف':'mobile','mobile':'mobile','سهل':'basic','basic':'basic','متوسط':'intermediate','intermediate':'intermediate','متقدم':'advanced','advanced':'advanced','بوب':'popup','بوباب':'popup','بوب اب':'popup','popup':'popup','toast':'toast','توست':'toast','tooltip':'tooltip','تلميح':'tooltip','popover':'popover','اشعار':'notification','إشعار':'notification','notification':'notification','حذف':'delete','delete':'delete','سلة':'trash','مهملات':'trash','trash':'trash','استعاده':'restore','استعادة':'restore'};
function norm(t=''){return String(t).toLowerCase().replace(/[أإآ]/g,'ا').replace(/ة/g,'ه').replace(/[ًٌٍَُِّْـ]/g,'').replace(/[^\u0000-\u007F\u0600-\u06FF]+/g,' ').trim()}
function tokens(t){return norm(t).split(/\s+/).filter(Boolean).map(x=>synonyms[x]||x)}
function score(s,ts){if(!ts.length)return 1;let cat=categories.find(x=>x.id===s.category),src=sourceById[s.sourceReference],name=tokens(s.name),tags=s.tags.map(t=>synonyms[norm(t)]||norm(t)),style=tokens(s.style),category=tokens([s.category,cat?.ar,cat?.en].join(' ')),desc=tokens(s.description||''),meta=tokens([s.technology,s.dependency,s.sourceReference,src?.name,s.motionMode,s.type].join(' ')),points=0,hits=0;for(let t of ts){let hit=false;if(name.some(x=>x===t||x.includes(t))){points+=7;hit=true}if(tags.some(x=>x===t||x.includes(t))){points+=6;hit=true}if(style.some(x=>x===t||x.includes(t))){points+=5;hit=true}if(category.some(x=>x===t||x.includes(t))){points+=4;hit=true}if(meta.some(x=>x===t||x.includes(t))){points+=4;hit=true}if(desc.some(x=>x===t||x.includes(t))){points+=2;hit=true}if(norm(s.id).includes(t)){points+=1;hit=true}if(hit)hits++}let need=ts.length<=2?1:Math.ceil(ts.length*.5);if(hits<need)return 0;if(state.q&&norm(s.name).includes(norm(state.q)))points+=8;return points}
function visible(){let list=samples.filter(available);if(state.pack!=='all')list=list.filter(s=>packOf(s)===state.pack);if(state.cat!=='all')list=list.filter(s=>s.category===state.cat);if(state.filter.startsWith('complexity:'))list=list.filter(s=>s.complexity===state.filter.split(':')[1]);else if(state.filter.startsWith('tag:'))list=list.filter(s=>s.tags.some(t=>norm(t)===state.filter.slice(4)));else if(state.filter==='special:new')list=list.filter(s=>s.addedAt==='2026-09-27').sort((a,b)=>b.id.localeCompare(a.id));else if(state.filter==='special:loop')list=list.filter(s=>s.motionMode==='Loop');else if(state.filter==='special:interaction')list=list.filter(s=>s.motionMode==='Interaction');else if(state.filter==='sort:used')list.sort((a,b)=>use(b)-use(a));else if(state.filter!=='All')list=list.filter(s=>s.style===state.filter||s.tags.some(t=>norm(t)===norm(state.filter)));let ts=tokens(state.q);if(ts.length)list=list.map(s=>({s,n:score(s,ts)})).filter(x=>x.n>0).sort((a,b)=>b.n-a.n||use(b.s)-use(a.s)).map(x=>x.s);else if(state.filter!=='sort:used'&&state.filter!=='special:new')list.sort((a,b)=>use(b)-use(a)||a.name.localeCompare(b.name));return list}
function suggestions(){let q=el.search.value.trim();if(!q){el.suggestions.hidden=true;return}let ts=tokens(q),list=samples.filter(s=>available(s)&&(state.pack==='all'||packOf(s)===state.pack)).map(s=>({s,n:score(s,ts)})).filter(x=>x.n>0).sort((a,b)=>b.n-a.n).slice(0,5);if(!list.length){el.suggestions.hidden=true;return}el.suggestions.innerHTML=list.map(({s})=>`<button data-suggest="${s.id}"><span>${s.name}</span><small>${s.id}</small></button>`).join('');el.suggestions.hidden=false}

let localSearchTimer=0;
function scheduleLocalSearch(){
  state.mode='library';state.q=el.search.value.trim();state.cat='all';state.filter='All';
  clearTimeout(localSearchTimer);
  localSearchTimer=setTimeout(()=>{
    resetGridWindow();$$('[data-view]').forEach(b=>b.classList.remove('active'));
    renderNav();renderFilters();renderGrid();header();suggestions();
  },120);
}
