import fs from 'node:fs';import path from 'node:path';
const root=process.cwd(),dist=path.join(root,'dist'),BASE='https://mmashharawi2021-cell.github.io/Library-/';
fs.rmSync(dist,{recursive:true,force:true});fs.mkdirSync(dist,{recursive:true});
for(const f of ['index.html','404.html','styles.css','app.js','data.js','feed.xml','manifest.webmanifest','icon.svg','robots.txt'])fs.copyFileSync(path.join(root,f),path.join(dist,f));
const raw=fs.readFileSync('data.js','utf8').replace(/^window\.UI_AR_DATA\s*=\s*/,'').replace(/;\s*$/,'');const d=JSON.parse(raw);const shell=fs.readFileSync('index.html','utf8');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function page(route,title,desc,indexable=true){const dir=path.join(dist,route);fs.mkdirSync(dir,{recursive:true});const url=BASE+route.replace(/\/+$/,'')+'/';let h=shell.replace(/<title>[\s\S]*?<\/title>/,`<title>${esc(title)}</title>`).replace(/<meta name="description" content="[^"]*">/,`<meta name="description" content="${esc(desc)}">`).replace(/<meta name="robots" content="[^"]*">/,`<meta name="robots" content="${indexable?'index,follow,max-image-preview:large':'noindex,follow'}">`).replace(/<link rel="canonical" href="[^"]*">/,`<link rel="canonical" href="${url}">`).replace(/<meta property="og:title" content="[^"]*">/,`<meta property="og:title" content="${esc(title)}">`).replace(/<meta property="og:description" content="[^"]*">/,`<meta property="og:description" content="${esc(desc)}">`).replace(/<meta property="og:url" content="[^"]*">/,`<meta property="og:url" content="${url}">`).replace(/<meta name="twitter:title" content="[^"]*">/,`<meta name="twitter:title" content="${esc(title)}">`).replace(/<meta name="twitter:description" content="[^"]*">/,`<meta name="twitter:description" content="${esc(desc)}">`);fs.writeFileSync(path.join(dir,'index.html'),h)}
for(const e of d.entries)page('element/'+e.slug,e.ar+' — '+e.en,e.description);
page('styles','ما اسم هذا الأسلوب؟ — UI بالعربي','أطلس الأنماط البصرية في واجهات المستخدم.');for(const s of d.styles)page('styles/'+s.slug,s.ar+' — '+s.en,s.desc);
page('compare','العناصر المتشابهة — UI بالعربي','مقارنات بين عناصر واجهة يكثر الخلط بينها.');for(const c of d.comparisons)page('vs/'+c.slug,c.title+' — UI بالعربي',c.answer);page('translate','جدول الترجمة — UI بالعربي','الاسم المرئي مقابل AppKit وSwiftUI.');page('methodology','المنهجية — UI بالعربي','كيف نتحقق من أسماء عناصر واجهة المستخدم.');page('guides','الأدلة — UI بالعربي','أدلة عملية لاختيار عالم المصطلحات الصحيح.');page('appkit-vs-swiftui','AppKit أم SwiftUI؟','دليل اختيار المصطلح الصحيح لمشروعات macOS.');page('swift-vs-electron','Swift أم Electron؟','دليل اختيار عالم المصطلحات المناسب.');page('glossary','قاموس المصطلحات — UI بالعربي','تعريفات عربية سريعة للمفاهيم التقنية المتكررة في تصميم وبرمجة واجهات المستخدم.');page('saved','المحفوظات — UI بالعربي','العناصر المحفوظة محليًا.',false);page('submit','اقترح عنصرًا — UI بالعربي','اقترح عنصر واجهة جديدًا للقاموس عبر نموذج منظم.');
const urls=[BASE,...d.entries.map(e=>BASE+'element/'+e.slug+'/'),BASE+'styles/',...d.styles.map(s=>BASE+'styles/'+s.slug+'/'),BASE+'compare/',...d.comparisons.map(c=>BASE+'vs/'+c.slug+'/'),BASE+'translate/',BASE+'methodology/',BASE+'guides/',BASE+'appkit-vs-swiftui/',BASE+'swift-vs-electron/',BASE+'glossary/',BASE+'submit/'];fs.writeFileSync(path.join(dist,'sitemap.xml'),'<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+urls.map(u=>'  <url><loc>'+u+'</loc></url>').join('\n')+'\n</urlset>');console.log(JSON.stringify({entries:d.entries.length,styles:d.styles.length,comparisons:d.comparisons.length,translations:d.translations.length,urls:urls.length}));