window.LibraryPackOrigin=[
  {
    "id": "DEV-ORG-001",
    "name": "Origin UI · Button With Icon",
    "category": "buttons",
    "style": "Animated",
    "tags": [
      "origin-ui",
      "button-with-icon",
      "buttons",
      "devto",
      "source-pack",
      "dev-quality-pass"
    ],
    "complexity": "advanced",
    "code": {
      "html": "<button class=\"devpack pack-org dq-button dq-icon-btn dqv-1\" type=\"button\"><i>↗</i><span>Button With Icon</span></button>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "button",
    "addedAt": "2026-09-27",
    "qualityTemplate": "button-icon",
    "qualityVariant": 1
  },
  {
    "id": "DEV-ORG-002",
    "name": "Origin UI · Loading Button",
    "category": "buttons",
    "style": "Animated",
    "tags": [
      "origin-ui",
      "loading-button",
      "buttons",
      "devto",
      "source-pack",
      "dev-quality-pass"
    ],
    "complexity": "basic",
    "code": {
      "html": "<button class=\"devpack pack-org dq-button dq-loading-btn dqv-1\" type=\"button\"><i></i><span>Loading Button</span></button>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "button",
    "addedAt": "2026-09-27",
    "qualityTemplate": "button-loading",
    "qualityVariant": 1
  },
  {
    "id": "DEV-ORG-003",
    "name": "Origin UI · Split Button",
    "category": "buttons",
    "style": "Animated",
    "tags": [
      "origin-ui",
      "split-button",
      "buttons",
      "devto",
      "source-pack",
      "dev-quality-pass"
    ],
    "complexity": "basic",
    "code": {
      "html": "<div class=\"devpack pack-org dq-button dq-split-btn dqv-1\"><button>Split Button</button><button>⌄</button></div>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "button",
    "addedAt": "2026-09-27",
    "qualityTemplate": "button-split",
    "qualityVariant": 1
  },
  {
    "id": "DEV-ORG-004",
    "name": "Origin UI · Copy Button",
    "category": "buttons",
    "style": "Animated",
    "tags": [
      "origin-ui",
      "copy-button",
      "buttons",
      "devto",
      "source-pack",
      "dev-quality-pass"
    ],
    "complexity": "intermediate",
    "code": {
      "html": "<button class=\"devpack pack-org dq-button dq-icon-btn dqv-2\" type=\"button\"><small class=\"dqv-kicker\">LIVE</small><i>↗</i><span>Copy Button</span></button>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "button",
    "addedAt": "2026-09-27",
    "qualityTemplate": "button-icon",
    "qualityVariant": 2
  },
  {
    "id": "DEV-ORG-005",
    "name": "Origin UI · Icon Button",
    "category": "buttons",
    "style": "Animated",
    "tags": [
      "origin-ui",
      "icon-button",
      "buttons",
      "devto",
      "source-pack",
      "dev-quality-pass"
    ],
    "complexity": "basic",
    "code": {
      "html": "<button class=\"devpack pack-org dq-button dq-icon-btn dqv-3\" type=\"button\"><i>↗</i><span>Icon Button</span><em class=\"dqv-state\">Ready</em></button>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "button",
    "addedAt": "2026-09-27",
    "qualityTemplate": "button-icon",
    "qualityVariant": 3
  },
  {
    "id": "DEV-ORG-006",
    "name": "Origin UI · Search Input",
    "category": "inputs",
    "style": "Form",
    "tags": [
      "origin-ui",
      "search-input",
      "inputs",
      "devto",
      "source-pack",
      "dev-quality-pass"
    ],
    "complexity": "basic",
    "code": {
      "html": "<label class=\"devpack pack-org dq-input dq-search dqv-1\"><span>⌕</span><input placeholder=\"Search Input\"><kbd>⌘K</kbd></label>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "form-control",
    "addedAt": "2026-09-27",
    "qualityTemplate": "input-search",
    "qualityVariant": 1
  },
  {
    "id": "DEV-ORG-007",
    "name": "Origin UI · Password Input",
    "category": "inputs",
    "style": "Form",
    "tags": [
      "origin-ui",
      "password-input",
      "inputs",
      "devto",
      "source-pack",
      "dev-quality-pass"
    ],
    "complexity": "intermediate",
    "code": {
      "html": "<label class=\"devpack pack-org dq-input dq-password dqv-1\"><b>Password Input</b><div><input type=\"password\" value=\"password\"><button type=\"button\">◉</button></div><span><i></i><i></i><i></i><i></i></span></label>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "form-control",
    "addedAt": "2026-09-27",
    "qualityTemplate": "input-password",
    "qualityVariant": 1
  },
  {
    "id": "DEV-ORG-008",
    "name": "Origin UI · Floating Label Input",
    "category": "inputs",
    "style": "Form",
    "tags": [
      "origin-ui",
      "floating-label-input",
      "inputs",
      "devto",
      "source-pack",
      "dev-quality-pass"
    ],
    "complexity": "advanced",
    "code": {
      "html": "<label class=\"devpack pack-org dq-input dq-field dqv-1\"><b>Floating Label Input</b><input placeholder=\"Enter value\"><small>Helper text</small></label>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "form-control",
    "addedAt": "2026-09-27",
    "qualityTemplate": "input-field",
    "qualityVariant": 1
  },
  {
    "id": "DEV-ORG-009",
    "name": "Origin UI · Inline Edit Input",
    "category": "inputs",
    "style": "Form",
    "tags": [
      "origin-ui",
      "inline-edit-input",
      "inputs",
      "devto",
      "source-pack",
      "dev-quality-pass"
    ],
    "complexity": "basic",
    "code": {
      "html": "<label class=\"devpack pack-org dq-input dq-field dqv-2\"><header class=\"dqv-head\"><small>LIVE</small><i></i></header><b>Inline Edit Input</b><input placeholder=\"Enter value\"><small>Helper text</small></label>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "form-control",
    "addedAt": "2026-09-27",
    "qualityTemplate": "input-field",
    "qualityVariant": 2
  },
  {
    "id": "DEV-ORG-010",
    "name": "Origin UI · OTP Input",
    "category": "inputs",
    "style": "Form",
    "tags": [
      "origin-ui",
      "otp-input",
      "inputs",
      "devto",
      "source-pack",
      "dev-quality-pass"
    ],
    "complexity": "intermediate",
    "code": {
      "html": "<div class=\"devpack pack-org dq-input dq-otp dqv-1\"><b>OTP Input</b><div><input maxlength=\"1\" value=\"4\"><input maxlength=\"1\" value=\"8\"><input maxlength=\"1\"><input maxlength=\"1\"></div><small>Enter verification code</small></div>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "form-control",
    "addedAt": "2026-09-27",
    "qualityTemplate": "input-otp",
    "qualityVariant": 1
  },
  {
    "id": "DEV-ORG-011",
    "name": "Origin UI · Tag Input",
    "category": "inputs",
    "style": "Form",
    "tags": [
      "origin-ui",
      "tag-input",
      "inputs",
      "devto",
      "source-pack",
      "dev-quality-pass"
    ],
    "complexity": "basic",
    "code": {
      "html": "<label class=\"devpack pack-org dq-input dq-field dqv-3\"><b>Tag Input</b><input placeholder=\"Enter value\"><small>Helper text</small><footer class=\"dqv-foot\"><small>Ready</small><i></i></footer></label>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "form-control",
    "addedAt": "2026-09-27",
    "qualityTemplate": "input-field",
    "qualityVariant": 3
  },
  {
    "id": "DEV-ORG-012",
    "name": "Origin UI · File Input",
    "category": "inputs",
    "style": "Form",
    "tags": [
      "origin-ui",
      "file-input",
      "inputs",
      "devto",
      "source-pack",
      "dev-quality-pass"
    ],
    "complexity": "basic",
    "code": {
      "html": "<label class=\"devpack pack-org dq-input dq-file-input dqv-1\"><input type=\"file\"><i>⇧</i><b>File Input</b><small>Drop file or browse</small><span><em></em></span></label>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "form-control",
    "addedAt": "2026-09-27",
    "qualityTemplate": "input-file",
    "qualityVariant": 1
  },
  {
    "id": "DEV-ORG-013",
    "name": "Origin UI · Select With Search",
    "category": "inputs",
    "style": "Form",
    "tags": [
      "origin-ui",
      "select-with-search",
      "inputs",
      "devto",
      "source-pack",
      "dev-quality-pass"
    ],
    "complexity": "intermediate",
    "code": {
      "html": "<label class=\"devpack pack-org dq-input dq-select dqv-1\"><b>Select With Search</b><div><input placeholder=\"Search options\"><button>⌄</button></div><span><i></i>Selected value</span></label>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "form-control",
    "addedAt": "2026-09-27",
    "qualityTemplate": "input-select",
    "qualityVariant": 1
  },
  {
    "id": "DEV-ORG-014",
    "name": "Origin UI · Multi Select",
    "category": "inputs",
    "style": "Form",
    "tags": [
      "origin-ui",
      "multi-select",
      "inputs",
      "devto",
      "source-pack",
      "dev-quality-pass"
    ],
    "complexity": "basic",
    "code": {
      "html": "<label class=\"devpack pack-org dq-input dq-select dqv-2\"><header class=\"dqv-head\"><small>LIVE</small><i></i></header><b>Multi Select</b><div><input placeholder=\"Search options\"><button>⌄</button></div><span><i></i>Selected value</span></label>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "form-control",
    "addedAt": "2026-09-27",
    "qualityTemplate": "input-select",
    "qualityVariant": 2
  },
  {
    "id": "DEV-ORG-015",
    "name": "Origin UI · Checkbox Card",
    "category": "inputs",
    "style": "Form",
    "tags": [
      "origin-ui",
      "checkbox-card",
      "inputs",
      "devto",
      "source-pack",
      "dev-quality-pass"
    ],
    "complexity": "advanced",
    "code": {
      "html": "<fieldset class=\"devpack pack-org dq-input dq-choice dqv-1\"><legend>Checkbox Card</legend><label><input type=\"checkbox\" checked><span>Primary option</span></label><label><input type=\"checkbox\"><span>Secondary option</span></label></fieldset>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "form-control",
    "addedAt": "2026-09-27",
    "qualityTemplate": "input-choice",
    "qualityVariant": 1
  },
  {
    "id": "DEV-ORG-016",
    "name": "Origin UI · Radio Card",
    "category": "inputs",
    "style": "Form",
    "tags": [
      "origin-ui",
      "radio-card",
      "inputs",
      "devto",
      "source-pack",
      "dev-quality-pass"
    ],
    "complexity": "intermediate",
    "code": {
      "html": "<fieldset class=\"devpack pack-org dq-input dq-choice dqv-2\"><header class=\"dqv-head\"><small>LIVE</small><i></i></header><legend>Radio Card</legend><label><input type=\"radio\" checked><span>Primary option</span></label><label><input type=\"radio\"><span>Secondary option</span></label></fieldset>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "form-control",
    "addedAt": "2026-09-27",
    "qualityTemplate": "input-choice",
    "qualityVariant": 2
  },
  {
    "id": "DEV-ORG-017",
    "name": "Origin UI · Switch Row",
    "category": "cards",
    "style": "Content",
    "tags": [
      "origin-ui",
      "switch-row",
      "cards",
      "devto",
      "source-pack",
      "dev-quality-pass"
    ],
    "complexity": "basic",
    "code": {
      "html": "<article class=\"devpack pack-org dq-card dq-switch-card dqv-1\"><div><b>Switch Row</b><small>Preference setting</small></div><button class=\"dq-switch\" type=\"button\"><i></i></button></article>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "component",
    "addedAt": "2026-09-27",
    "qualityTemplate": "card-switch",
    "qualityVariant": 1
  },
  {
    "id": "DEV-ORG-018",
    "name": "Origin UI · Range Slider",
    "category": "inputs",
    "style": "Form",
    "tags": [
      "origin-ui",
      "range-slider",
      "inputs",
      "devto",
      "source-pack",
      "dev-quality-pass"
    ],
    "complexity": "basic",
    "code": {
      "html": "<label class=\"devpack pack-org dq-input dq-range dqv-1\"><b>Range Slider</b><input type=\"range\" min=\"0\" max=\"100\" value=\"64\"><div><small>0</small><strong>64</strong><small>100</small></div></label>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "form-control",
    "addedAt": "2026-09-27",
    "qualityTemplate": "input-range",
    "qualityVariant": 1
  },
  {
    "id": "DEV-ORG-019",
    "name": "Origin UI · Date Input",
    "category": "inputs",
    "style": "Form",
    "tags": [
      "origin-ui",
      "date-input",
      "inputs",
      "devto",
      "source-pack",
      "dev-quality-pass"
    ],
    "complexity": "intermediate",
    "code": {
      "html": "<label class=\"devpack pack-org dq-input dq-special dqv-1\"><b>Date Input</b><div><i>◫</i><input value=\"2026-09-28\"></div></label>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "form-control",
    "addedAt": "2026-09-27",
    "qualityTemplate": "input-special",
    "qualityVariant": 1
  },
  {
    "id": "DEV-ORG-020",
    "name": "Origin UI · Time Input",
    "category": "inputs",
    "style": "Form",
    "tags": [
      "origin-ui",
      "time-input",
      "inputs",
      "devto",
      "source-pack",
      "dev-quality-pass"
    ],
    "complexity": "basic",
    "code": {
      "html": "<label class=\"devpack pack-org dq-input dq-special dqv-2\"><header class=\"dqv-head\"><small>LIVE</small><i></i></header><b>Time Input</b><div><i>◷</i><input value=\"12:30\"></div></label>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "form-control",
    "addedAt": "2026-09-27",
    "qualityTemplate": "input-special",
    "qualityVariant": 2
  },
  {
    "id": "DEV-ORG-021",
    "name": "Origin UI · Textarea Counter",
    "category": "inputs",
    "style": "Form",
    "tags": [
      "origin-ui",
      "textarea-counter",
      "inputs",
      "devto",
      "source-pack",
      "dev-quality-pass"
    ],
    "complexity": "basic",
    "code": {
      "html": "<label class=\"devpack pack-org dq-input dq-textarea dqv-1\"><b>Textarea Counter</b><textarea placeholder=\"Write something...\"></textarea><small>24 / 140</small></label>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "form-control",
    "addedAt": "2026-09-27",
    "qualityTemplate": "input-textarea",
    "qualityVariant": 1
  },
  {
    "id": "DEV-ORG-022",
    "name": "Origin UI · Form Validation",
    "category": "inputs",
    "style": "Form",
    "tags": [
      "origin-ui",
      "form-validation",
      "inputs",
      "devto",
      "source-pack",
      "dev-quality-pass"
    ],
    "complexity": "advanced",
    "code": {
      "html": "<label class=\"devpack pack-org dq-input dq-validation dqv-1\"><b>Form Validation</b><input value=\"mohanad@example.com\"><span>✓ Looks good</span></label>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "form-control",
    "addedAt": "2026-09-27",
    "qualityTemplate": "input-validation",
    "qualityVariant": 1
  },
  {
    "id": "DEV-ORG-023",
    "name": "Origin UI · Command Menu",
    "category": "menus",
    "style": "Actions",
    "tags": [
      "origin-ui",
      "command-menu",
      "menus",
      "devto",
      "source-pack",
      "dev-quality-pass"
    ],
    "complexity": "basic",
    "code": {
      "html": "<div class=\"devpack pack-org dq-menu dq-command dqv-1\"><label>⌕<input placeholder=\"Command Menu\"><kbd>⌘K</kbd></label><button class=\"active\">Open component <small>↵</small></button><button>Search library</button></div>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "menu",
    "addedAt": "2026-09-27",
    "qualityTemplate": "menu-command",
    "qualityVariant": 1
  },
  {
    "id": "DEV-ORG-024",
    "name": "Origin UI · Context Menu",
    "category": "menus",
    "style": "Actions",
    "tags": [
      "origin-ui",
      "context-menu",
      "menus",
      "devto",
      "source-pack",
      "dev-quality-pass"
    ],
    "complexity": "basic",
    "code": {
      "html": "<div class=\"devpack pack-org dq-menu dq-context dqv-1\"><header><i></i><b>Context Menu</b></header><button>Open</button><button>Duplicate</button><button class=\"danger\">Delete</button></div>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "menu",
    "addedAt": "2026-09-27",
    "qualityTemplate": "menu-context",
    "qualityVariant": 1
  },
  {
    "id": "DEV-ORG-025",
    "name": "Origin UI · Dropdown Menu",
    "category": "menus",
    "style": "Actions",
    "tags": [
      "origin-ui",
      "dropdown-menu",
      "menus",
      "devto",
      "source-pack",
      "dev-quality-pass"
    ],
    "complexity": "intermediate",
    "code": {
      "html": "<div class=\"devpack pack-org dq-menu dq-dropdown dqv-1\"><button class=\"dq-trigger\">Dropdown Menu<i>⌄</i></button><div class=\"dq-options\"><span class=\"active\">First option</span><span>Second option</span><span>Third option</span></div></div>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "menu",
    "addedAt": "2026-09-27",
    "qualityTemplate": "menu-dropdown",
    "qualityVariant": 1
  },
  {
    "id": "DEV-ORG-026",
    "name": "Origin UI · Action Menu",
    "category": "menus",
    "style": "Actions",
    "tags": [
      "origin-ui",
      "action-menu",
      "menus",
      "devto",
      "source-pack",
      "dev-quality-pass"
    ],
    "complexity": "basic",
    "code": {
      "html": "<div class=\"devpack pack-org dq-menu dq-context dqv-2\"><header class=\"dqv-head\"><small>LIVE</small><i></i></header><header><i></i><b>Action Menu</b></header><button>Open</button><button>Duplicate</button><button class=\"danger\">Delete</button></div>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "menu",
    "addedAt": "2026-09-27",
    "qualityTemplate": "menu-context",
    "qualityVariant": 2
  },
  {
    "id": "DEV-ORG-027",
    "name": "Origin UI · Profile Menu",
    "category": "menus",
    "style": "Actions",
    "tags": [
      "origin-ui",
      "profile-menu",
      "menus",
      "devto",
      "source-pack",
      "dev-quality-pass"
    ],
    "complexity": "basic",
    "code": {
      "html": "<div class=\"devpack pack-org dq-menu dq-context dqv-3\"><header><i></i><b>Profile Menu</b></header><button>Open</button><button>Duplicate</button><button class=\"danger\">Delete</button><footer class=\"dqv-foot\"><small>Ready</small><i></i></footer></div>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "menu",
    "addedAt": "2026-09-27",
    "qualityTemplate": "menu-context",
    "qualityVariant": 3
  },
  {
    "id": "DEV-ORG-028",
    "name": "Origin UI · Pagination",
    "category": "nav",
    "style": "Minimal",
    "tags": [
      "origin-ui",
      "pagination",
      "nav",
      "devto",
      "source-pack",
      "dev-quality-pass"
    ],
    "complexity": "intermediate",
    "code": {
      "html": "<nav class=\"devpack pack-org dq-nav dq-pagination dqv-1\"><button>‹</button><button class=\"active\">1</button><button>2</button><button>3</button><button>›</button></nav>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "navigation",
    "addedAt": "2026-09-27",
    "qualityTemplate": "nav-pagination",
    "qualityVariant": 1
  },
  {
    "id": "DEV-ORG-029",
    "name": "Origin UI · Breadcrumb",
    "category": "nav",
    "style": "Minimal",
    "tags": [
      "origin-ui",
      "breadcrumb",
      "nav",
      "devto",
      "source-pack",
      "dev-quality-pass"
    ],
    "complexity": "advanced",
    "code": {
      "html": "<nav class=\"devpack pack-org dq-nav dq-breadcrumb dqv-1\"><a>Home</a><i>/</i><a>Library</a><i>/</i><b>Breadcrumb</b></nav>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "navigation",
    "addedAt": "2026-09-27",
    "qualityTemplate": "nav-breadcrumb",
    "qualityVariant": 1
  },
  {
    "id": "DEV-ORG-030",
    "name": "Origin UI · Stepper",
    "category": "nav",
    "style": "Minimal",
    "tags": [
      "origin-ui",
      "stepper",
      "nav",
      "devto",
      "source-pack",
      "dev-quality-pass"
    ],
    "complexity": "basic",
    "code": {
      "html": "<nav class=\"devpack pack-org dq-nav dq-steps dqv-1\"><span class=\"done\"><i>1</i><b>Start</b></span><span class=\"active\"><i>2</i><b>Stepper</b></span><span><i>3</i><b>Done</b></span></nav>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "navigation",
    "addedAt": "2026-09-27",
    "qualityTemplate": "nav-steps",
    "qualityVariant": 1
  },
  {
    "id": "DEV-ORG-031",
    "name": "Origin UI · Sidebar Navigation",
    "category": "nav",
    "style": "Minimal",
    "tags": [
      "origin-ui",
      "sidebar-navigation",
      "nav",
      "devto",
      "source-pack",
      "dev-quality-pass"
    ],
    "complexity": "intermediate",
    "code": {
      "html": "<nav class=\"devpack pack-org dq-nav dq-sidebar dqv-1\"><header><i>M</i><b>Sidebar Navigation</b></header><a class=\"active\">Overview</a><a>Components</a><a>Settings</a></nav>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "navigation",
    "addedAt": "2026-09-27",
    "qualityTemplate": "nav-sidebar",
    "qualityVariant": 1
  },
  {
    "id": "DEV-ORG-032",
    "name": "Origin UI · Top Navigation",
    "category": "nav",
    "style": "Minimal",
    "tags": [
      "origin-ui",
      "top-navigation",
      "nav",
      "devto",
      "source-pack",
      "dev-quality-pass"
    ],
    "complexity": "basic",
    "code": {
      "html": "<nav class=\"devpack pack-org dq-nav dq-navbar dqv-1\"><b>Top Navigation</b><div><a class=\"active\">Home</a><a>Library</a><a>About</a></div><button>Start</button></nav>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "navigation",
    "addedAt": "2026-09-27",
    "qualityTemplate": "nav-navbar",
    "qualityVariant": 1
  },
  {
    "id": "DEV-ORG-033",
    "name": "Origin UI · Tabs",
    "category": "tabs",
    "style": "Tabs",
    "tags": [
      "origin-ui",
      "tabs",
      "tabs",
      "devto",
      "source-pack",
      "dev-quality-pass"
    ],
    "complexity": "basic",
    "code": {
      "html": "<div class=\"devpack pack-org dq-tabs dq-tabbar dqv-1\"><div class=\"dq-tablist\"><button class=\"active\">Tabs</button><button>Preview</button><button>Code</button></div><div class=\"dq-tabpanel\">Active panel</div></div>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "disclosure",
    "addedAt": "2026-09-27",
    "qualityTemplate": "tabs-tabs",
    "qualityVariant": 1
  },
  {
    "id": "DEV-ORG-034",
    "name": "Origin UI · Segmented Control",
    "category": "tabs",
    "style": "Tabs",
    "tags": [
      "origin-ui",
      "segmented-control",
      "tabs",
      "devto",
      "source-pack",
      "dev-quality-pass"
    ],
    "complexity": "intermediate",
    "code": {
      "html": "<div class=\"devpack pack-org dq-tabs dq-segmented dqv-1\"><button class=\"active\">Overview</button><button>Details</button><button>Activity</button></div>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "disclosure",
    "addedAt": "2026-09-27",
    "qualityTemplate": "tabs-segmented",
    "qualityVariant": 1
  },
  {
    "id": "DEV-ORG-035",
    "name": "Origin UI · Accordion",
    "category": "tabs",
    "style": "Tabs",
    "tags": [
      "origin-ui",
      "accordion",
      "tabs",
      "devto",
      "source-pack",
      "dev-quality-pass"
    ],
    "complexity": "basic",
    "code": {
      "html": "<div class=\"devpack pack-org dq-tabs dq-accordion dqv-1\"><button class=\"dq-acc-head active\" type=\"button\"><span>Accordion</span><i>+</i></button><div class=\"dq-acc-panel\">Reusable disclosure content</div><button class=\"dq-acc-head\" type=\"button\"><span>Second item</span><i>+</i></button></div>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "disclosure",
    "addedAt": "2026-09-27",
    "qualityTemplate": "tabs-accordion",
    "qualityVariant": 1
  },
  {
    "id": "DEV-ORG-036",
    "name": "Origin UI · Collapsible",
    "category": "tabs",
    "style": "Tabs",
    "tags": [
      "origin-ui",
      "collapsible",
      "tabs",
      "devto",
      "source-pack",
      "dev-quality-pass"
    ],
    "complexity": "advanced",
    "code": {
      "html": "<div class=\"devpack pack-org dq-tabs dq-accordion dqv-2\"><header class=\"dqv-head\"><small>LIVE</small><i></i></header><button class=\"dq-acc-head active\" type=\"button\"><span>Collapsible</span><i>+</i></button><div class=\"dq-acc-panel\">Reusable disclosure content</div><button class=\"dq-acc-head\" type=\"button\"><span>Second item</span><i>+</i></button></div>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "disclosure",
    "addedAt": "2026-09-27",
    "qualityTemplate": "tabs-accordion",
    "qualityVariant": 2
  },
  {
    "id": "DEV-ORG-037",
    "name": "Origin UI · Dialog",
    "category": "modals",
    "style": "Popover",
    "tags": [
      "origin-ui",
      "dialog",
      "modals",
      "devto",
      "source-pack",
      "dev-quality-pass"
    ],
    "complexity": "intermediate",
    "code": {
      "html": "<div class=\"devpack pack-org dq-overlay dq-dialog dqv-1\"><header><b>Dialog</b><button>×</button></header><p>Contextual dialog content goes here.</p><footer><button>Cancel</button><button>Continue</button></footer></div>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "overlay",
    "addedAt": "2026-09-27",
    "qualityTemplate": "overlay-dialog",
    "qualityVariant": 1
  },
  {
    "id": "DEV-ORG-038",
    "name": "Origin UI · Alert Dialog",
    "category": "modals",
    "style": "Popover",
    "tags": [
      "origin-ui",
      "alert-dialog",
      "modals",
      "devto",
      "source-pack",
      "dev-quality-pass"
    ],
    "complexity": "basic",
    "code": {
      "html": "<div class=\"devpack pack-org dq-overlay dq-dialog dq-alert-dialog dqv-1\"><i>!</i><h4>Alert Dialog</h4><p>This action requires confirmation.</p><footer><button>Cancel</button><button>Confirm</button></footer></div>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "overlay",
    "addedAt": "2026-09-27",
    "qualityTemplate": "overlay-alert",
    "qualityVariant": 1
  },
  {
    "id": "DEV-ORG-039",
    "name": "Origin UI · Drawer",
    "category": "modals",
    "style": "Popover",
    "tags": [
      "origin-ui",
      "drawer",
      "modals",
      "devto",
      "source-pack",
      "dev-quality-pass"
    ],
    "complexity": "basic",
    "code": {
      "html": "<div class=\"devpack pack-org dq-overlay dq-drawer dqv-1\"><header><b>Drawer</b><button>×</button></header><div><span></span><span></span><span></span></div><footer><button>Cancel</button><button>Save</button></footer></div>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "overlay",
    "addedAt": "2026-09-27",
    "qualityTemplate": "overlay-drawer",
    "qualityVariant": 1
  },
  {
    "id": "DEV-ORG-040",
    "name": "Origin UI · Popover",
    "category": "modals",
    "style": "Popover",
    "tags": [
      "origin-ui",
      "popover",
      "modals",
      "devto",
      "source-pack",
      "dev-quality-pass"
    ],
    "complexity": "intermediate",
    "code": {
      "html": "<div class=\"devpack pack-org dq-overlay dq-popover dqv-1\"><button>•••</button><aside><b>Popover</b><span>First action</span><span>Second action</span></aside></div>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "overlay",
    "addedAt": "2026-09-27",
    "qualityTemplate": "overlay-popover",
    "qualityVariant": 1
  },
  {
    "id": "DEV-ORG-041",
    "name": "Origin UI · Tooltip",
    "category": "modals",
    "style": "Popover",
    "tags": [
      "origin-ui",
      "tooltip",
      "modals",
      "devto",
      "source-pack",
      "dev-quality-pass"
    ],
    "complexity": "basic",
    "code": {
      "html": "<div class=\"devpack pack-org dq-overlay dq-tooltip dqv-1\"><button>Hover me</button><span>Tooltip</span></div>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "overlay",
    "addedAt": "2026-09-27",
    "qualityTemplate": "overlay-tooltip",
    "qualityVariant": 1
  },
  {
    "id": "DEV-ORG-042",
    "name": "Origin UI · Toast",
    "category": "modals",
    "style": "Popover",
    "tags": [
      "origin-ui",
      "toast",
      "modals",
      "devto",
      "source-pack",
      "dev-quality-pass"
    ],
    "complexity": "basic",
    "code": {
      "html": "<div class=\"devpack pack-org dq-overlay dq-toast dqv-1\"><i>✓</i><div><b>Toast</b><small>Operation completed successfully</small></div><button>×</button></div>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "overlay",
    "addedAt": "2026-09-27",
    "qualityTemplate": "overlay-toast",
    "qualityVariant": 1
  },
  {
    "id": "DEV-ORG-043",
    "name": "Origin UI · Notification",
    "category": "modals",
    "style": "Popover",
    "tags": [
      "origin-ui",
      "notification",
      "modals",
      "devto",
      "source-pack",
      "dev-quality-pass"
    ],
    "complexity": "advanced",
    "code": {
      "html": "<div class=\"devpack pack-org dq-overlay dq-toast dqv-2\"><header class=\"dqv-head\"><small>LIVE</small><i></i></header><i>✓</i><div><b>Notification</b><small>Operation completed successfully</small></div><button>×</button></div>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "overlay",
    "addedAt": "2026-09-27",
    "qualityTemplate": "overlay-toast",
    "qualityVariant": 2
  },
  {
    "id": "DEV-ORG-044",
    "name": "Origin UI · Data Table",
    "category": "data",
    "style": "Table",
    "tags": [
      "origin-ui",
      "data-table",
      "data",
      "devto",
      "source-pack",
      "dev-quality-pass"
    ],
    "complexity": "basic",
    "code": {
      "html": "<div class=\"devpack pack-org dq-data dq-table dqv-1\"><header><b>Data Table</b><input placeholder=\"Filter\"></header><div class=\"dq-row head\"><span>Name</span><span>Status</span><span>Value</span></div><div class=\"dq-row\"><span>Alpha</span><span>Active</span><span>84</span></div><div class=\"dq-row\"><span>Beta</span><span>Review</span><span>61</span></div></div>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "data-display",
    "addedAt": "2026-09-27",
    "qualityTemplate": "data-table",
    "qualityVariant": 1
  },
  {
    "id": "DEV-ORG-045",
    "name": "Origin UI · Sortable Table",
    "category": "data",
    "style": "Table",
    "tags": [
      "origin-ui",
      "sortable-table",
      "data",
      "devto",
      "source-pack",
      "dev-quality-pass"
    ],
    "complexity": "basic",
    "code": {
      "html": "<div class=\"devpack pack-org dq-data dq-table dqv-2\"><header class=\"dqv-head\"><small>LIVE</small><i></i></header><header><b>Sortable Table</b><input placeholder=\"Filter\"></header><div class=\"dq-row head\"><span>Name</span><span>Status</span><span>Value</span></div><div class=\"dq-row\"><span>Alpha</span><span>Active</span><span>84</span></div><div class=\"dq-row\"><span>Beta</span><span>Review</span><span>61</span></div></div>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "data-display",
    "addedAt": "2026-09-27",
    "qualityTemplate": "data-table",
    "qualityVariant": 2
  },
  {
    "id": "DEV-ORG-046",
    "name": "Origin UI · Filter Table",
    "category": "data",
    "style": "Table",
    "tags": [
      "origin-ui",
      "filter-table",
      "data",
      "devto",
      "source-pack",
      "dev-quality-pass"
    ],
    "complexity": "intermediate",
    "code": {
      "html": "<div class=\"devpack pack-org dq-data dq-table dqv-3\"><header><b>Filter Table</b><input placeholder=\"Filter\"></header><div class=\"dq-row head\"><span>Name</span><span>Status</span><span>Value</span></div><div class=\"dq-row\"><span>Alpha</span><span>Active</span><span>84</span></div><div class=\"dq-row\"><span>Beta</span><span>Review</span><span>61</span></div><footer class=\"dqv-foot\"><small>Ready</small><i></i></footer></div>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "data-display",
    "addedAt": "2026-09-27",
    "qualityTemplate": "data-table",
    "qualityVariant": 3
  },
  {
    "id": "DEV-ORG-047",
    "name": "Origin UI · Stat Card",
    "category": "data",
    "style": "Table",
    "tags": [
      "origin-ui",
      "stat-card",
      "data",
      "devto",
      "source-pack",
      "dev-quality-pass"
    ],
    "complexity": "basic",
    "code": {
      "html": "<div class=\"devpack pack-org dq-data dq-stat dqv-1\"><small>Stat Card</small><strong>24.8K</strong><span>+12.4%</span><svg viewBox=\"0 0 90 28\"><polyline points=\"2,23 18,18 30,20 45,8 60,12 75,5 88,7\"></polyline></svg></div>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "data-display",
    "addedAt": "2026-09-27",
    "qualityTemplate": "data-stat",
    "qualityVariant": 1
  },
  {
    "id": "DEV-ORG-048",
    "name": "Origin UI · KPI Card",
    "category": "data",
    "style": "Table",
    "tags": [
      "origin-ui",
      "kpi-card",
      "data",
      "devto",
      "source-pack",
      "dev-quality-pass"
    ],
    "complexity": "basic",
    "code": {
      "html": "<div class=\"devpack pack-org dq-data dq-stat dqv-2\"><header class=\"dqv-head\"><small>LIVE</small><i></i></header><small>KPI Card</small><strong>24.8K</strong><span>+12.4%</span><svg viewBox=\"0 0 90 28\"><polyline points=\"2,23 18,18 30,20 45,8 60,12 75,5 88,7\"></polyline></svg></div>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "data-display",
    "addedAt": "2026-09-27",
    "qualityTemplate": "data-stat",
    "qualityVariant": 2
  },
  {
    "id": "DEV-ORG-049",
    "name": "Origin UI · Timeline",
    "category": "inputs",
    "style": "Form",
    "tags": [
      "origin-ui",
      "timeline",
      "inputs",
      "devto",
      "source-pack",
      "dev-quality-pass"
    ],
    "complexity": "intermediate",
    "code": {
      "html": "<label class=\"devpack pack-org dq-input dq-special dqv-3\"><b>Timeline</b><div><i>◷</i><input value=\"12:30\"></div><footer class=\"dqv-foot\"><small>Ready</small><i></i></footer></label>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "form-control",
    "addedAt": "2026-09-27",
    "qualityTemplate": "input-special",
    "qualityVariant": 3
  },
  {
    "id": "DEV-ORG-050",
    "name": "Origin UI · Calendar",
    "category": "data",
    "style": "Table",
    "tags": [
      "origin-ui",
      "calendar",
      "data",
      "devto",
      "source-pack",
      "dev-quality-pass"
    ],
    "complexity": "advanced",
    "code": {
      "html": "<div class=\"devpack pack-org dq-data dq-calendar dqv-1\"><header><button>‹</button><b>September</b><button>›</button></header><div class=\"dq-days\"><span>1</span><span>2</span><span>3</span><span>4</span><span>5</span><span>6</span><span>7</span><span class=\"active\">8</span><span>9</span><span>10</span><span>11</span><span>12</span><span>13</span><span>14</span></div></div>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "data-display",
    "addedAt": "2026-09-27",
    "qualityTemplate": "data-calendar",
    "qualityVariant": 1
  },
  {
    "id": "DEV-ORG-051",
    "name": "Origin UI · Activity Feed",
    "category": "data",
    "style": "Table",
    "tags": [
      "origin-ui",
      "activity-feed",
      "data",
      "devto",
      "source-pack",
      "dev-quality-pass"
    ],
    "complexity": "basic",
    "code": {
      "html": "<div class=\"devpack pack-org dq-data dq-feed dqv-1\"><b>Activity Feed</b><span><i></i><em>Created component</em><small>now</small></span><span><i></i><em>Updated library</em><small>2m</small></span><span><i></i><em>Published changes</em><small>5m</small></span></div>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "data-display",
    "addedAt": "2026-09-27",
    "qualityTemplate": "data-feed",
    "qualityVariant": 1
  },
  {
    "id": "DEV-ORG-052",
    "name": "Origin UI · Empty State",
    "category": "data",
    "style": "Table",
    "tags": [
      "origin-ui",
      "empty-state",
      "data",
      "devto",
      "source-pack",
      "dev-quality-pass"
    ],
    "complexity": "intermediate",
    "code": {
      "html": "<div class=\"devpack pack-org dq-data dq-stat dqv-3\"><small>Empty State</small><strong>24.8K</strong><span>+12.4%</span><svg viewBox=\"0 0 90 28\"><polyline points=\"2,23 18,18 30,20 45,8 60,12 75,5 88,7\"></polyline></svg><footer class=\"dqv-foot\"><small>Ready</small><i></i></footer></div>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "data-display",
    "addedAt": "2026-09-27",
    "qualityTemplate": "data-stat",
    "qualityVariant": 3
  },
  {
    "id": "DEV-ORG-053",
    "name": "Origin UI · File Card",
    "category": "cards",
    "style": "Feature",
    "tags": [
      "origin-ui",
      "file-card",
      "cards",
      "devto",
      "source-pack",
      "dev-quality-pass"
    ],
    "complexity": "basic",
    "code": {
      "html": "<article class=\"devpack pack-org dq-card dq-file dqv-1\"><i>DOC</i><div><b>File Card</b><small>2.4 MB · Updated now</small></div><button>⋮</button></article>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "card",
    "addedAt": "2026-09-27",
    "qualityTemplate": "card-file",
    "qualityVariant": 1
  },
  {
    "id": "DEV-ORG-054",
    "name": "Origin UI · User Card",
    "category": "cards",
    "style": "Feature",
    "tags": [
      "origin-ui",
      "user-card",
      "cards",
      "devto",
      "source-pack",
      "dev-quality-pass"
    ],
    "complexity": "basic",
    "code": {
      "html": "<article class=\"devpack pack-org dq-card dq-profile dqv-1\"><div class=\"dq-avatar\"></div><div><b>User Card</b><small>Product Designer</small></div><button>Follow</button></article>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "card",
    "addedAt": "2026-09-27",
    "qualityTemplate": "card-profile",
    "qualityVariant": 1
  },
  {
    "id": "DEV-ORG-055",
    "name": "Origin UI · Pricing Card",
    "category": "sections",
    "style": "Bento",
    "tags": [
      "origin-ui",
      "pricing-card",
      "sections",
      "devto",
      "source-pack",
      "dev-quality-pass"
    ],
    "complexity": "intermediate",
    "code": {
      "html": "<section class=\"devpack pack-org dq-section dq-pricing dqv-1\"><small>PRO</small><h3>$24</h3><b>Pricing Card</b><ul><li>Unlimited components</li><li>Export code</li><li>Priority updates</li></ul><button>Choose plan</button></section>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "layout",
    "addedAt": "2026-09-27",
    "qualityTemplate": "section-pricing",
    "qualityVariant": 1
  },
  {
    "id": "DEV-ORG-056",
    "name": "Origin UI · Feature Card",
    "category": "cards",
    "style": "Feature",
    "tags": [
      "origin-ui",
      "feature-card",
      "cards",
      "devto",
      "source-pack",
      "dev-quality-pass"
    ],
    "complexity": "basic",
    "code": {
      "html": "<article class=\"devpack pack-org dq-card dq-content-card dqv-1\"><header><small>Component</small><i></i></header><h4>Feature Card</h4><p>Reusable content pattern for interfaces.</p><footer><span>Details</span><button>↗</button></footer></article>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "card",
    "addedAt": "2026-09-27",
    "qualityTemplate": "card-content",
    "qualityVariant": 1
  }
];
