window.LibraryPackOrigin=[
  {
    "id": "DEV-ORG-001",
    "name": "Origin UI · Button With Icon",
    "category": "buttons",
    "style": "Animated",
    "tags": [
      "origin-ui",
      "button-with-icon",
      "buttons",
      "devto",
      "source-pack"
    ],
    "complexity": "advanced",
    "code": {
      "html": "<button class=\"devpack pack-org kind-buttons variant-0 button-with-icon\" type=\"button\"><i></i><span>Origin UI · Button With Icon</span></button>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "button",
    "addedAt": "2026-09-27"
  },
  {
    "id": "DEV-ORG-002",
    "name": "Origin UI · Loading Button",
    "category": "buttons",
    "style": "Animated",
    "tags": [
      "origin-ui",
      "loading-button",
      "buttons",
      "devto",
      "source-pack"
    ],
    "complexity": "basic",
    "code": {
      "html": "<button class=\"devpack pack-org kind-buttons variant-1 loading-button\" type=\"button\"><i></i><span>Origin UI · Loading Button</span></button>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "button",
    "addedAt": "2026-09-27"
  },
  {
    "id": "DEV-ORG-003",
    "name": "Origin UI · Split Button",
    "category": "buttons",
    "style": "Animated",
    "tags": [
      "origin-ui",
      "split-button",
      "buttons",
      "devto",
      "source-pack"
    ],
    "complexity": "basic",
    "code": {
      "html": "<button class=\"devpack pack-org kind-buttons variant-2 split-button\" type=\"button\"><i></i><span>Origin UI · Split Button</span></button>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "button",
    "addedAt": "2026-09-27"
  },
  {
    "id": "DEV-ORG-004",
    "name": "Origin UI · Copy Button",
    "category": "buttons",
    "style": "Animated",
    "tags": [
      "origin-ui",
      "copy-button",
      "buttons",
      "devto",
      "source-pack"
    ],
    "complexity": "intermediate",
    "code": {
      "html": "<button class=\"devpack pack-org kind-buttons variant-3 copy-button\" type=\"button\"><i></i><span>Origin UI · Copy Button</span></button>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "button",
    "addedAt": "2026-09-27"
  },
  {
    "id": "DEV-ORG-005",
    "name": "Origin UI · Icon Button",
    "category": "buttons",
    "style": "Animated",
    "tags": [
      "origin-ui",
      "icon-button",
      "buttons",
      "devto",
      "source-pack"
    ],
    "complexity": "basic",
    "code": {
      "html": "<button class=\"devpack pack-org kind-buttons variant-4 icon-button\" type=\"button\"><i></i><span>Origin UI · Icon Button</span></button>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "button",
    "addedAt": "2026-09-27"
  },
  {
    "id": "DEV-ORG-006",
    "name": "Origin UI · Search Input",
    "category": "inputs",
    "style": "Form",
    "tags": [
      "origin-ui",
      "search-input",
      "inputs",
      "devto",
      "source-pack"
    ],
    "complexity": "basic",
    "code": {
      "html": "<label class=\"devpack pack-org kind-inputs variant-5 search-input\"><b>Search Input</b><input placeholder=\"Origin UI field\"><small>Origin UI reference</small></label>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "form-control",
    "addedAt": "2026-09-27"
  },
  {
    "id": "DEV-ORG-007",
    "name": "Origin UI · Password Input",
    "category": "inputs",
    "style": "Form",
    "tags": [
      "origin-ui",
      "password-input",
      "inputs",
      "devto",
      "source-pack"
    ],
    "complexity": "intermediate",
    "code": {
      "html": "<label class=\"devpack pack-org kind-inputs variant-6 password-input\"><b>Password Input</b><input placeholder=\"Origin UI field\"><small>Origin UI reference</small></label>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "form-control",
    "addedAt": "2026-09-27"
  },
  {
    "id": "DEV-ORG-008",
    "name": "Origin UI · Floating Label Input",
    "category": "inputs",
    "style": "Form",
    "tags": [
      "origin-ui",
      "floating-label-input",
      "inputs",
      "devto",
      "source-pack"
    ],
    "complexity": "advanced",
    "code": {
      "html": "<label class=\"devpack pack-org kind-inputs variant-7 floating-label-input\"><b>Floating Label Input</b><input placeholder=\"Origin UI field\"><small>Origin UI reference</small></label>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "form-control",
    "addedAt": "2026-09-27"
  },
  {
    "id": "DEV-ORG-009",
    "name": "Origin UI · Inline Edit Input",
    "category": "inputs",
    "style": "Form",
    "tags": [
      "origin-ui",
      "inline-edit-input",
      "inputs",
      "devto",
      "source-pack"
    ],
    "complexity": "basic",
    "code": {
      "html": "<label class=\"devpack pack-org kind-inputs variant-0 inline-edit-input\"><b>Inline Edit Input</b><input placeholder=\"Origin UI field\"><small>Origin UI reference</small></label>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "form-control",
    "addedAt": "2026-09-27"
  },
  {
    "id": "DEV-ORG-010",
    "name": "Origin UI · OTP Input",
    "category": "inputs",
    "style": "Form",
    "tags": [
      "origin-ui",
      "otp-input",
      "inputs",
      "devto",
      "source-pack"
    ],
    "complexity": "intermediate",
    "code": {
      "html": "<label class=\"devpack pack-org kind-inputs variant-1 otp-input\"><b>OTP Input</b><input placeholder=\"Origin UI field\"><small>Origin UI reference</small></label>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "form-control",
    "addedAt": "2026-09-27"
  },
  {
    "id": "DEV-ORG-011",
    "name": "Origin UI · Tag Input",
    "category": "inputs",
    "style": "Form",
    "tags": [
      "origin-ui",
      "tag-input",
      "inputs",
      "devto",
      "source-pack"
    ],
    "complexity": "basic",
    "code": {
      "html": "<label class=\"devpack pack-org kind-inputs variant-2 tag-input\"><b>Tag Input</b><input placeholder=\"Origin UI field\"><small>Origin UI reference</small></label>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "form-control",
    "addedAt": "2026-09-27"
  },
  {
    "id": "DEV-ORG-012",
    "name": "Origin UI · File Input",
    "category": "inputs",
    "style": "Form",
    "tags": [
      "origin-ui",
      "file-input",
      "inputs",
      "devto",
      "source-pack"
    ],
    "complexity": "basic",
    "code": {
      "html": "<label class=\"devpack pack-org kind-inputs variant-3 file-input\"><b>File Input</b><input placeholder=\"Origin UI field\"><small>Origin UI reference</small></label>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "form-control",
    "addedAt": "2026-09-27"
  },
  {
    "id": "DEV-ORG-013",
    "name": "Origin UI · Select With Search",
    "category": "inputs",
    "style": "Form",
    "tags": [
      "origin-ui",
      "select-with-search",
      "inputs",
      "devto",
      "source-pack"
    ],
    "complexity": "intermediate",
    "code": {
      "html": "<label class=\"devpack pack-org kind-inputs variant-4 select-with-search\"><b>Select With Search</b><input placeholder=\"Origin UI field\"><small>Origin UI reference</small></label>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "form-control",
    "addedAt": "2026-09-27"
  },
  {
    "id": "DEV-ORG-014",
    "name": "Origin UI · Multi Select",
    "category": "inputs",
    "style": "Form",
    "tags": [
      "origin-ui",
      "multi-select",
      "inputs",
      "devto",
      "source-pack"
    ],
    "complexity": "basic",
    "code": {
      "html": "<label class=\"devpack pack-org kind-inputs variant-5 multi-select\"><b>Multi Select</b><input placeholder=\"Origin UI field\"><small>Origin UI reference</small></label>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "form-control",
    "addedAt": "2026-09-27"
  },
  {
    "id": "DEV-ORG-015",
    "name": "Origin UI · Checkbox Card",
    "category": "inputs",
    "style": "Form",
    "tags": [
      "origin-ui",
      "checkbox-card",
      "inputs",
      "devto",
      "source-pack"
    ],
    "complexity": "advanced",
    "code": {
      "html": "<label class=\"devpack pack-org kind-inputs variant-6 checkbox-card\"><b>Checkbox Card</b><input placeholder=\"Origin UI field\"><small>Origin UI reference</small></label>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "form-control",
    "addedAt": "2026-09-27"
  },
  {
    "id": "DEV-ORG-016",
    "name": "Origin UI · Radio Card",
    "category": "inputs",
    "style": "Form",
    "tags": [
      "origin-ui",
      "radio-card",
      "inputs",
      "devto",
      "source-pack"
    ],
    "complexity": "intermediate",
    "code": {
      "html": "<label class=\"devpack pack-org kind-inputs variant-7 radio-card\"><b>Radio Card</b><input placeholder=\"Origin UI field\"><small>Origin UI reference</small></label>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "form-control",
    "addedAt": "2026-09-27"
  },
  {
    "id": "DEV-ORG-017",
    "name": "Origin UI · Switch Row",
    "category": "cards",
    "style": "Content",
    "tags": [
      "origin-ui",
      "switch-row",
      "cards",
      "devto",
      "source-pack"
    ],
    "complexity": "basic",
    "code": {
      "html": "<article class=\"devpack pack-org kind-cards variant-0 switch-row\"><small>Origin UI</small><h4>Switch Row</h4><p>Reusable component pattern.</p></article>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "component",
    "addedAt": "2026-09-27"
  },
  {
    "id": "DEV-ORG-018",
    "name": "Origin UI · Range Slider",
    "category": "inputs",
    "style": "Form",
    "tags": [
      "origin-ui",
      "range-slider",
      "inputs",
      "devto",
      "source-pack"
    ],
    "complexity": "basic",
    "code": {
      "html": "<label class=\"devpack pack-org kind-inputs variant-1 range-slider\"><b>Range Slider</b><input placeholder=\"Origin UI field\"><small>Origin UI reference</small></label>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "form-control",
    "addedAt": "2026-09-27"
  },
  {
    "id": "DEV-ORG-019",
    "name": "Origin UI · Date Input",
    "category": "inputs",
    "style": "Form",
    "tags": [
      "origin-ui",
      "date-input",
      "inputs",
      "devto",
      "source-pack"
    ],
    "complexity": "intermediate",
    "code": {
      "html": "<label class=\"devpack pack-org kind-inputs variant-2 date-input\"><b>Date Input</b><input placeholder=\"Origin UI field\"><small>Origin UI reference</small></label>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "form-control",
    "addedAt": "2026-09-27"
  },
  {
    "id": "DEV-ORG-020",
    "name": "Origin UI · Time Input",
    "category": "inputs",
    "style": "Form",
    "tags": [
      "origin-ui",
      "time-input",
      "inputs",
      "devto",
      "source-pack"
    ],
    "complexity": "basic",
    "code": {
      "html": "<label class=\"devpack pack-org kind-inputs variant-3 time-input\"><b>Time Input</b><input placeholder=\"Origin UI field\"><small>Origin UI reference</small></label>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "form-control",
    "addedAt": "2026-09-27"
  },
  {
    "id": "DEV-ORG-021",
    "name": "Origin UI · Textarea Counter",
    "category": "inputs",
    "style": "Form",
    "tags": [
      "origin-ui",
      "textarea-counter",
      "inputs",
      "devto",
      "source-pack"
    ],
    "complexity": "basic",
    "code": {
      "html": "<label class=\"devpack pack-org kind-inputs variant-4 textarea-counter\"><b>Textarea Counter</b><input placeholder=\"Origin UI field\"><small>Origin UI reference</small></label>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "form-control",
    "addedAt": "2026-09-27"
  },
  {
    "id": "DEV-ORG-022",
    "name": "Origin UI · Form Validation",
    "category": "inputs",
    "style": "Form",
    "tags": [
      "origin-ui",
      "form-validation",
      "inputs",
      "devto",
      "source-pack"
    ],
    "complexity": "advanced",
    "code": {
      "html": "<label class=\"devpack pack-org kind-inputs variant-5 form-validation\"><b>Form Validation</b><input placeholder=\"Origin UI field\"><small>Origin UI reference</small></label>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "form-control",
    "addedAt": "2026-09-27"
  },
  {
    "id": "DEV-ORG-023",
    "name": "Origin UI · Command Menu",
    "category": "menus",
    "style": "Actions",
    "tags": [
      "origin-ui",
      "command-menu",
      "menus",
      "devto",
      "source-pack"
    ],
    "complexity": "basic",
    "code": {
      "html": "<div class=\"devpack pack-org kind-menus variant-6 command-menu\"><b>Command Menu</b><span>الخيار الأول</span><span>الخيار الثاني</span><span>الخيار الثالث</span></div>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "menu",
    "addedAt": "2026-09-27"
  },
  {
    "id": "DEV-ORG-024",
    "name": "Origin UI · Context Menu",
    "category": "menus",
    "style": "Actions",
    "tags": [
      "origin-ui",
      "context-menu",
      "menus",
      "devto",
      "source-pack"
    ],
    "complexity": "basic",
    "code": {
      "html": "<div class=\"devpack pack-org kind-menus variant-7 context-menu\"><b>Context Menu</b><span>الخيار الأول</span><span>الخيار الثاني</span><span>الخيار الثالث</span></div>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "menu",
    "addedAt": "2026-09-27"
  },
  {
    "id": "DEV-ORG-025",
    "name": "Origin UI · Dropdown Menu",
    "category": "menus",
    "style": "Actions",
    "tags": [
      "origin-ui",
      "dropdown-menu",
      "menus",
      "devto",
      "source-pack"
    ],
    "complexity": "intermediate",
    "code": {
      "html": "<div class=\"devpack pack-org kind-menus variant-0 dropdown-menu\"><b>Dropdown Menu</b><span>الخيار الأول</span><span>الخيار الثاني</span><span>الخيار الثالث</span></div>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "menu",
    "addedAt": "2026-09-27"
  },
  {
    "id": "DEV-ORG-026",
    "name": "Origin UI · Action Menu",
    "category": "menus",
    "style": "Actions",
    "tags": [
      "origin-ui",
      "action-menu",
      "menus",
      "devto",
      "source-pack"
    ],
    "complexity": "basic",
    "code": {
      "html": "<div class=\"devpack pack-org kind-menus variant-1 action-menu\"><b>Action Menu</b><span>الخيار الأول</span><span>الخيار الثاني</span><span>الخيار الثالث</span></div>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "menu",
    "addedAt": "2026-09-27"
  },
  {
    "id": "DEV-ORG-027",
    "name": "Origin UI · Profile Menu",
    "category": "menus",
    "style": "Actions",
    "tags": [
      "origin-ui",
      "profile-menu",
      "menus",
      "devto",
      "source-pack"
    ],
    "complexity": "basic",
    "code": {
      "html": "<div class=\"devpack pack-org kind-menus variant-2 profile-menu\"><b>Profile Menu</b><span>الخيار الأول</span><span>الخيار الثاني</span><span>الخيار الثالث</span></div>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "menu",
    "addedAt": "2026-09-27"
  },
  {
    "id": "DEV-ORG-028",
    "name": "Origin UI · Pagination",
    "category": "nav",
    "style": "Minimal",
    "tags": [
      "origin-ui",
      "pagination",
      "nav",
      "devto",
      "source-pack"
    ],
    "complexity": "intermediate",
    "code": {
      "html": "<nav class=\"devpack pack-org kind-nav variant-3 pagination\"><b>Pagination</b><span>الرئيسية</span><span>العناصر</span><span>الإعدادات</span></nav>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "navigation",
    "addedAt": "2026-09-27"
  },
  {
    "id": "DEV-ORG-029",
    "name": "Origin UI · Breadcrumb",
    "category": "nav",
    "style": "Minimal",
    "tags": [
      "origin-ui",
      "breadcrumb",
      "nav",
      "devto",
      "source-pack"
    ],
    "complexity": "advanced",
    "code": {
      "html": "<nav class=\"devpack pack-org kind-nav variant-4 breadcrumb\"><b>Breadcrumb</b><span>الرئيسية</span><span>العناصر</span><span>الإعدادات</span></nav>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "navigation",
    "addedAt": "2026-09-27"
  },
  {
    "id": "DEV-ORG-030",
    "name": "Origin UI · Stepper",
    "category": "nav",
    "style": "Minimal",
    "tags": [
      "origin-ui",
      "stepper",
      "nav",
      "devto",
      "source-pack"
    ],
    "complexity": "basic",
    "code": {
      "html": "<nav class=\"devpack pack-org kind-nav variant-5 stepper\"><b>Stepper</b><span>الرئيسية</span><span>العناصر</span><span>الإعدادات</span></nav>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "navigation",
    "addedAt": "2026-09-27"
  },
  {
    "id": "DEV-ORG-031",
    "name": "Origin UI · Sidebar Navigation",
    "category": "nav",
    "style": "Minimal",
    "tags": [
      "origin-ui",
      "sidebar-navigation",
      "nav",
      "devto",
      "source-pack"
    ],
    "complexity": "intermediate",
    "code": {
      "html": "<nav class=\"devpack pack-org kind-nav variant-6 sidebar-navigation\"><b>Sidebar Navigation</b><span>الرئيسية</span><span>العناصر</span><span>الإعدادات</span></nav>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "navigation",
    "addedAt": "2026-09-27"
  },
  {
    "id": "DEV-ORG-032",
    "name": "Origin UI · Top Navigation",
    "category": "nav",
    "style": "Minimal",
    "tags": [
      "origin-ui",
      "top-navigation",
      "nav",
      "devto",
      "source-pack"
    ],
    "complexity": "basic",
    "code": {
      "html": "<nav class=\"devpack pack-org kind-nav variant-7 top-navigation\"><b>Top Navigation</b><span>الرئيسية</span><span>العناصر</span><span>الإعدادات</span></nav>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "navigation",
    "addedAt": "2026-09-27"
  },
  {
    "id": "DEV-ORG-033",
    "name": "Origin UI · Tabs",
    "category": "tabs",
    "style": "Tabs",
    "tags": [
      "origin-ui",
      "tabs",
      "tabs",
      "devto",
      "source-pack"
    ],
    "complexity": "basic",
    "code": {
      "html": "<div class=\"devpack pack-org kind-tabs variant-0 tabs\"><button class=\"active\">Tabs</button><button>Option B</button><button>Option C</button></div>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "disclosure",
    "addedAt": "2026-09-27"
  },
  {
    "id": "DEV-ORG-034",
    "name": "Origin UI · Segmented Control",
    "category": "tabs",
    "style": "Tabs",
    "tags": [
      "origin-ui",
      "segmented-control",
      "tabs",
      "devto",
      "source-pack"
    ],
    "complexity": "intermediate",
    "code": {
      "html": "<div class=\"devpack pack-org kind-tabs variant-1 segmented-control\"><button class=\"active\">Segmented Control</button><button>Option B</button><button>Option C</button></div>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "disclosure",
    "addedAt": "2026-09-27"
  },
  {
    "id": "DEV-ORG-035",
    "name": "Origin UI · Accordion",
    "category": "tabs",
    "style": "Tabs",
    "tags": [
      "origin-ui",
      "accordion",
      "tabs",
      "devto",
      "source-pack"
    ],
    "complexity": "basic",
    "code": {
      "html": "<div class=\"devpack pack-org kind-tabs variant-2 accordion\"><button class=\"active\">Accordion</button><button>Option B</button><button>Option C</button></div>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "disclosure",
    "addedAt": "2026-09-27"
  },
  {
    "id": "DEV-ORG-036",
    "name": "Origin UI · Collapsible",
    "category": "tabs",
    "style": "Tabs",
    "tags": [
      "origin-ui",
      "collapsible",
      "tabs",
      "devto",
      "source-pack"
    ],
    "complexity": "advanced",
    "code": {
      "html": "<div class=\"devpack pack-org kind-tabs variant-3 collapsible\"><button class=\"active\">Collapsible</button><button>Option B</button><button>Option C</button></div>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "disclosure",
    "addedAt": "2026-09-27"
  },
  {
    "id": "DEV-ORG-037",
    "name": "Origin UI · Dialog",
    "category": "modals",
    "style": "Popover",
    "tags": [
      "origin-ui",
      "dialog",
      "modals",
      "devto",
      "source-pack"
    ],
    "complexity": "intermediate",
    "code": {
      "html": "<div class=\"devpack pack-org kind-modals variant-4 dialog\"><small>Origin UI</small><b>Dialog</b><p>Contextual overlay pattern.</p><button>متابعة</button></div>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "overlay",
    "addedAt": "2026-09-27"
  },
  {
    "id": "DEV-ORG-038",
    "name": "Origin UI · Alert Dialog",
    "category": "modals",
    "style": "Popover",
    "tags": [
      "origin-ui",
      "alert-dialog",
      "modals",
      "devto",
      "source-pack"
    ],
    "complexity": "basic",
    "code": {
      "html": "<div class=\"devpack pack-org kind-modals variant-5 alert-dialog\"><small>Origin UI</small><b>Alert Dialog</b><p>Contextual overlay pattern.</p><button>متابعة</button></div>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "overlay",
    "addedAt": "2026-09-27"
  },
  {
    "id": "DEV-ORG-039",
    "name": "Origin UI · Drawer",
    "category": "modals",
    "style": "Popover",
    "tags": [
      "origin-ui",
      "drawer",
      "modals",
      "devto",
      "source-pack"
    ],
    "complexity": "basic",
    "code": {
      "html": "<div class=\"devpack pack-org kind-modals variant-6 drawer\"><small>Origin UI</small><b>Drawer</b><p>Contextual overlay pattern.</p><button>متابعة</button></div>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "overlay",
    "addedAt": "2026-09-27"
  },
  {
    "id": "DEV-ORG-040",
    "name": "Origin UI · Popover",
    "category": "modals",
    "style": "Popover",
    "tags": [
      "origin-ui",
      "popover",
      "modals",
      "devto",
      "source-pack"
    ],
    "complexity": "intermediate",
    "code": {
      "html": "<div class=\"devpack pack-org kind-modals variant-7 popover\"><small>Origin UI</small><b>Popover</b><p>Contextual overlay pattern.</p><button>متابعة</button></div>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "overlay",
    "addedAt": "2026-09-27"
  },
  {
    "id": "DEV-ORG-041",
    "name": "Origin UI · Tooltip",
    "category": "modals",
    "style": "Popover",
    "tags": [
      "origin-ui",
      "tooltip",
      "modals",
      "devto",
      "source-pack"
    ],
    "complexity": "basic",
    "code": {
      "html": "<div class=\"devpack pack-org kind-modals variant-0 tooltip\"><small>Origin UI</small><b>Tooltip</b><p>Contextual overlay pattern.</p><button>متابعة</button></div>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "overlay",
    "addedAt": "2026-09-27"
  },
  {
    "id": "DEV-ORG-042",
    "name": "Origin UI · Toast",
    "category": "modals",
    "style": "Popover",
    "tags": [
      "origin-ui",
      "toast",
      "modals",
      "devto",
      "source-pack"
    ],
    "complexity": "basic",
    "code": {
      "html": "<div class=\"devpack pack-org kind-modals variant-1 toast\"><small>Origin UI</small><b>Toast</b><p>Contextual overlay pattern.</p><button>متابعة</button></div>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "overlay",
    "addedAt": "2026-09-27"
  },
  {
    "id": "DEV-ORG-043",
    "name": "Origin UI · Notification",
    "category": "modals",
    "style": "Popover",
    "tags": [
      "origin-ui",
      "notification",
      "modals",
      "devto",
      "source-pack"
    ],
    "complexity": "advanced",
    "code": {
      "html": "<div class=\"devpack pack-org kind-modals variant-2 notification\"><small>Origin UI</small><b>Notification</b><p>Contextual overlay pattern.</p><button>متابعة</button></div>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "overlay",
    "addedAt": "2026-09-27"
  },
  {
    "id": "DEV-ORG-044",
    "name": "Origin UI · Data Table",
    "category": "data",
    "style": "Table",
    "tags": [
      "origin-ui",
      "data-table",
      "data",
      "devto",
      "source-pack"
    ],
    "complexity": "basic",
    "code": {
      "html": "<div class=\"devpack pack-org kind-data variant-3 data-table\"><header><b>Data Table</b><span>72%</span></header><i></i><i></i><i></i><small>Origin UI data pattern</small></div>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "data-display",
    "addedAt": "2026-09-27"
  },
  {
    "id": "DEV-ORG-045",
    "name": "Origin UI · Sortable Table",
    "category": "data",
    "style": "Table",
    "tags": [
      "origin-ui",
      "sortable-table",
      "data",
      "devto",
      "source-pack"
    ],
    "complexity": "basic",
    "code": {
      "html": "<div class=\"devpack pack-org kind-data variant-4 sortable-table\"><header><b>Sortable Table</b><span>72%</span></header><i></i><i></i><i></i><small>Origin UI data pattern</small></div>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "data-display",
    "addedAt": "2026-09-27"
  },
  {
    "id": "DEV-ORG-046",
    "name": "Origin UI · Filter Table",
    "category": "data",
    "style": "Table",
    "tags": [
      "origin-ui",
      "filter-table",
      "data",
      "devto",
      "source-pack"
    ],
    "complexity": "intermediate",
    "code": {
      "html": "<div class=\"devpack pack-org kind-data variant-5 filter-table\"><header><b>Filter Table</b><span>72%</span></header><i></i><i></i><i></i><small>Origin UI data pattern</small></div>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "data-display",
    "addedAt": "2026-09-27"
  },
  {
    "id": "DEV-ORG-047",
    "name": "Origin UI · Stat Card",
    "category": "data",
    "style": "Table",
    "tags": [
      "origin-ui",
      "stat-card",
      "data",
      "devto",
      "source-pack"
    ],
    "complexity": "basic",
    "code": {
      "html": "<div class=\"devpack pack-org kind-data variant-6 stat-card\"><header><b>Stat Card</b><span>72%</span></header><i></i><i></i><i></i><small>Origin UI data pattern</small></div>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "data-display",
    "addedAt": "2026-09-27"
  },
  {
    "id": "DEV-ORG-048",
    "name": "Origin UI · KPI Card",
    "category": "data",
    "style": "Table",
    "tags": [
      "origin-ui",
      "kpi-card",
      "data",
      "devto",
      "source-pack"
    ],
    "complexity": "basic",
    "code": {
      "html": "<div class=\"devpack pack-org kind-data variant-7 kpi-card\"><header><b>KPI Card</b><span>72%</span></header><i></i><i></i><i></i><small>Origin UI data pattern</small></div>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "data-display",
    "addedAt": "2026-09-27"
  },
  {
    "id": "DEV-ORG-049",
    "name": "Origin UI · Timeline",
    "category": "inputs",
    "style": "Form",
    "tags": [
      "origin-ui",
      "timeline",
      "inputs",
      "devto",
      "source-pack"
    ],
    "complexity": "intermediate",
    "code": {
      "html": "<label class=\"devpack pack-org kind-inputs variant-0 timeline\"><b>Timeline</b><input placeholder=\"Origin UI field\"><small>Origin UI reference</small></label>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "form-control",
    "addedAt": "2026-09-27"
  },
  {
    "id": "DEV-ORG-050",
    "name": "Origin UI · Calendar",
    "category": "data",
    "style": "Table",
    "tags": [
      "origin-ui",
      "calendar",
      "data",
      "devto",
      "source-pack"
    ],
    "complexity": "advanced",
    "code": {
      "html": "<div class=\"devpack pack-org kind-data variant-1 calendar\"><header><b>Calendar</b><span>72%</span></header><i></i><i></i><i></i><small>Origin UI data pattern</small></div>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "data-display",
    "addedAt": "2026-09-27"
  },
  {
    "id": "DEV-ORG-051",
    "name": "Origin UI · Activity Feed",
    "category": "data",
    "style": "Table",
    "tags": [
      "origin-ui",
      "activity-feed",
      "data",
      "devto",
      "source-pack"
    ],
    "complexity": "basic",
    "code": {
      "html": "<div class=\"devpack pack-org kind-data variant-2 activity-feed\"><header><b>Activity Feed</b><span>72%</span></header><i></i><i></i><i></i><small>Origin UI data pattern</small></div>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "data-display",
    "addedAt": "2026-09-27"
  },
  {
    "id": "DEV-ORG-052",
    "name": "Origin UI · Empty State",
    "category": "data",
    "style": "Table",
    "tags": [
      "origin-ui",
      "empty-state",
      "data",
      "devto",
      "source-pack"
    ],
    "complexity": "intermediate",
    "code": {
      "html": "<div class=\"devpack pack-org kind-data variant-3 empty-state\"><header><b>Empty State</b><span>72%</span></header><i></i><i></i><i></i><small>Origin UI data pattern</small></div>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "data-display",
    "addedAt": "2026-09-27"
  },
  {
    "id": "DEV-ORG-053",
    "name": "Origin UI · File Card",
    "category": "cards",
    "style": "Feature",
    "tags": [
      "origin-ui",
      "file-card",
      "cards",
      "devto",
      "source-pack"
    ],
    "complexity": "basic",
    "code": {
      "html": "<article class=\"devpack pack-org kind-cards variant-4 file-card\"><small>Origin UI</small><h4>File Card</h4><p>Reusable component pattern.</p></article>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "card",
    "addedAt": "2026-09-27"
  },
  {
    "id": "DEV-ORG-054",
    "name": "Origin UI · User Card",
    "category": "cards",
    "style": "Feature",
    "tags": [
      "origin-ui",
      "user-card",
      "cards",
      "devto",
      "source-pack"
    ],
    "complexity": "basic",
    "code": {
      "html": "<article class=\"devpack pack-org kind-cards variant-5 user-card\"><small>Origin UI</small><h4>User Card</h4><p>Reusable component pattern.</p></article>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "card",
    "addedAt": "2026-09-27"
  },
  {
    "id": "DEV-ORG-055",
    "name": "Origin UI · Pricing Card",
    "category": "sections",
    "style": "Bento",
    "tags": [
      "origin-ui",
      "pricing-card",
      "sections",
      "devto",
      "source-pack"
    ],
    "complexity": "intermediate",
    "code": {
      "html": "<section class=\"devpack pack-org kind-sections variant-6 pricing-card\"><header>Pricing Card</header><main><b>Origin UI</b><span>Reusable layout block</span></main><footer>01 · 02 · 03</footer></section>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "layout",
    "addedAt": "2026-09-27"
  },
  {
    "id": "DEV-ORG-056",
    "name": "Origin UI · Feature Card",
    "category": "cards",
    "style": "Feature",
    "tags": [
      "origin-ui",
      "feature-card",
      "cards",
      "devto",
      "source-pack"
    ],
    "complexity": "basic",
    "code": {
      "html": "<article class=\"devpack pack-org kind-cards variant-7 feature-card\"><small>Origin UI</small><h4>Feature Card</h4><p>Reusable component pattern.</p></article>",
      "css": "",
      "js": "",
      "react": "",
      "tailwind": ""
    },
    "favorite": false,
    "usage": 0,
    "description": "تنفيذ أصلي مصنف ضمن Origin UI بعد اكتشاف المصدر عبر DEV.to.",
    "playground": {},
    "technology": "HTML + CSS",
    "dependency": "None",
    "sourceReference": "originui-official",
    "motionMode": "Interaction",
    "type": "card",
    "addedAt": "2026-09-27"
  }
];
