/* Library navigation, filtering, search and counters. */
function toast(t){el.toast.textContent=t;el.toast.classList.add('show');setTimeout(()=>el.toast.classList.remove('show'),1500)}
function renderNav(){let meta=catalogMeta().filter(metaAvailable).filter(s=>state.pack==='all'||packOf(s)===state.pack);el.nav.innerHTML=`<button class="side-link ${state.cat==='all'&&state.mode==='library'?'active':''}" data-cat="all"><span>⌂</span><b>كل العناصر</b><em>${meta.length}</em></button>`+categories.map(cat=>`<button class="side-link ${state.cat===cat.id&&state.mode==='library'?'active':''}" data-cat="${cat.id}"><span>${cat.icon}</span><b>${cat.ar}</b><em>${meta.filter(s=>s.category===cat.id).length}</em></button>`).join('')}
function renderOverview(){let scoped=samples.filter(s=>available(s)&&(state.pack==='all'||packOf(s)===state.pack)),list=categories.filter(cat=>scoped.some(s=>s.category===cat.id)).sort((a,b)=>catUse(b.id)-catUse(a.id)).slice(0,10),max=Math.max(1,...list.map(cat=>catUse(cat.id)));el.catGrid.innerHTML=list.map((cat,i)=>`<button class="category-card" data-cat="${cat.id}"><span class="rank">${String(i+1).padStart(2,'0')}</span><span class="cat-icon">${cat.icon}</span><strong>${cat.ar}</strong><small>${cat.en} · ${scoped.filter(s=>s.category===cat.id).length} نماذج</small><div class="meter"><span style="width:${Math.max(7,catUse(cat.id)/max*100)}%"></span></div></button>`).join('')}
function renderFilters(){let cat=categories.find(x=>x.id===state.cat),styles=cat?cat.styles:['All','Minimal','Glass','Dark','Animated','Dashboard','Hover'],base=samples.filter(s=>available(s)&&(state.pack==='all'||packOf(s)===state.pack)&&(state.cat==='all'||s.category===state.cat)),tagCounts={};base.forEach(s=>(s.tags||[]).forEach(t=>tagCounts[norm(t)]=(tagCounts[norm(t)]||0)+1));let topTags=Object.entries(tagCounts).sort((a,b)=>b[1]-a[1]).slice(0,6).map(([t])=>t);let styleButtons=styles.map(s=>`<button class="filter ${state.filter===s?'active':''}" data-filter="${s}">${s==='All'?'الكل':s}</button>`).join('');let levels=[['basic','سهل'],['intermediate','متوسط'],['advanced','متقدم']].map(([k,l])=>`<button class="filter complexity ${state.filter==='complexity:'+k?'active':''}" data-filter="complexity:${k}">${l}</button>`).join('');let smart=[['special:new','الجديد'],['special:loop','Loop'],['special:interaction','Interactive'],['sort:used','الأكثر استخدامًا']].map(([k,l])=>`<button class="filter smart ${state.filter===k?'active':''}" data-filter="${k}">${l}</button>`).join('');let tags=topTags.map(t=>`<button class="filter tag-filter ${state.filter==='tag:'+t?'active':''}" data-filter="tag:${t}">#${t}</button>`).join('');el.filters.innerHTML=styleButtons+'<span class="filter-sep"></span>'+levels+'<span class="filter-sep"></span>'+smart+(tags?'<span class="filter-sep"></span>'+tags:'')}
function score(s,ts){if(!ts.length)return 1;let cat=categories.find(x=>x.id===s.category),src=sourceById[s.sourceReference],name=tokens(s.name),tags=s.tags.map(t=>synonyms[norm(t)]||norm(t)),style=tokens(s.style),category=tokens([s.category,cat?.ar,cat?.en].join(' ')),desc=tokens(s.description||''),meta=tokens([s.technology,s.dependency,s.sourceReference,src?.name,s.motionMode,s.type].join(' ')),points=0,hits=0;for(let t of ts){let hit=false;if(name.some(x=>x===t||x.includes(t))){points+=7;hit=true}if(tags.some(x=>x===t||x.includes(t))){points+=6;hit=true}if(style.some(x=>x===t||x.includes(t))){points+=5;hit=true}if(category.some(x=>x===t||x.includes(t))){points+=4;hit=true}if(meta.some(x=>x===t||x.includes(t))){points+=4;hit=true}if(desc.some(x=>x===t||x.includes(t))){points+=2;hit=true}if(norm(s.id).includes(t)){points+=1;hit=true}if(hit)hits++}let need=ts.length<=2?1:Math.ceil(ts.length*.5);if(hits<need)return 0;if(state.q&&norm(s.name).includes(norm(state.q)))points+=8;return points}
function visible(){let list=samples.filter(available);if(state.pack!=='all')list=list.filter(s=>packOf(s)===state.pack);if(state.cat!=='all')list=list.filter(s=>s.category===state.cat);if(state.filter.startsWith('complexity:'))list=list.filter(s=>s.complexity===state.filter.split(':')[1]);else if(state.filter.startsWith('tag:'))list=list.filter(s=>s.tags.some(t=>norm(t)===state.filter.slice(4)));else if(state.filter==='special:new')list=list.filter(s=>s.addedAt==='2026-09-27').sort((a,b)=>b.id.localeCompare(a.id));else if(state.filter==='special:loop')list=list.filter(s=>s.motionMode==='Loop');else if(state.filter==='special:interaction')list=list.filter(s=>s.motionMode==='Interaction');else if(state.filter==='sort:used')list.sort((a,b)=>use(b)-use(a));else if(state.filter!=='All')list=list.filter(s=>s.style===state.filter||s.tags.some(t=>norm(t)===norm(state.filter)));let ts=tokens(state.q);if(ts.length)list=list.map(s=>({s,n:score(s,ts)})).filter(x=>x.n>0).sort((a,b)=>b.n-a.n||use(b.s)-use(a.s)).map(x=>x.s);else if(state.filter!=='sort:used'&&state.filter!=='special:new')list.sort((a,b)=>use(b)-use(a)||a.name.localeCompare(b.name));return list}
function header(){let cat=categories.find(x=>x.id===state.cat),availableCount=catalogMeta().filter(metaAvailable).length,modeTitle={favorites:'المفضلة',recent:'آخر استخدام',trash:'سلة المحذوفات',collections:'المجموعات'}[state.mode];el.title.textContent=modeTitle||(state.q?`نتائج البحث عن: ${state.q}`:cat?cat.ar:'كل النماذج');el.eyebrow.textContent=state.mode==='trash'?'Trash':state.mode==='collections'?'Collections':state.mode!=='library'?'مساحتي':cat?cat.en:'المكتبة الكاملة';$('#componentTotal').textContent=availableCount;$('#categoryTotal').textContent=categories.length;$('#usageTotal').textContent=Object.values(state.usage).reduce((a,n)=>a+Number(n),0);$('#favCount').textContent=[...state.favorites].filter(id=>{let s=samples.find(x=>x.id===id);return s&&available(s)}).length;$('#recentCount').textContent=state.recent.filter(id=>{let s=samples.find(x=>x.id===id);return s&&available(s)}).length;$('#collectionCount').textContent=Object.keys(state.collections).length+5;$('#trashCount').textContent=state.trash.size;$('#clearSearch').hidden=!state.q;syncPackFilter()}
function renderAll(){resetGridWindow();renderNav();renderOverview();renderFilters();renderGrid();header();syncPackFilter()}
function setCat(id){state.mode='library';state.cat=id;state.filter='All';state.q='';el.search.value='';$$('[data-view]').forEach(b=>b.classList.remove('active'));renderAll();$('#library').scrollIntoView({behavior:'smooth'});$('#sidebar').classList.remove('open')}
function recent(id){state.recent=[id,...state.recent.filter(x=>x!==id)].slice(0,12);persist();header()}
function mark(id){state.usage[id]=Number(state.usage[id]||0)+1;recent(id);persist();renderOverview();renderGrid();header()}
function toggleFav(id){state.favorites.has(id)?state.favorites.delete(id):state.favorites.add(id);persist();renderGrid();header();if(state.active?.id===id)el.fav.textContent=state.favorites.has(id)?'♥':'♡';toast(state.favorites.has(id)?'تمت الإضافة للمفضلة':'تمت الإزالة من المفضلة')}

function showView(v){if(v==='collections'){showCollectionPreset('dashboard');return}state.mode=v;state.cat='all';state.pack='all';state.q='';state.filter='All';resetGridWindow();el.search.value='';let list=[];if(v==='favorites')list=[...state.favorites].map(id=>samples.find(s=>s.id===id)).filter(s=>s&&available(s));else if(v==='recent')list=state.recent.map(id=>samples.find(s=>s.id===id)).filter(s=>s&&available(s));else if(v==='trash')list=[...state.trash].map(id=>samples.find(s=>s.id===id)).filter(s=>s&&!state.purged.has(s.id));renderNav();renderFilters();$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v));el.title.textContent=v==='favorites'?'المفضلة':v==='recent'?'آخر استخدام':'سلة المحذوفات';el.eyebrow.textContent=v==='trash'?'Trash':'مساحتي';renderGrid(list);header();$('#library').scrollIntoView({behavior:'smooth'});$('#sidebar').classList.remove('open')}
function suggestions(){let q=el.search.value.trim();if(!q){el.suggestions.hidden=true;return}let ts=tokens(q),list=samples.filter(s=>available(s)&&(state.pack==='all'||packOf(s)===state.pack)).map(s=>({s,n:score(s,ts)})).filter(x=>x.n>0).sort((a,b)=>b.n-a.n).slice(0,5);if(!list.length){el.suggestions.hidden=true;return}el.suggestions.innerHTML=list.map(({s})=>`<button data-suggest="${s.id}"><span>${s.name}</span><small>${s.id}</small></button>`).join('');el.suggestions.hidden=false}
