/* Library navigation, filtering, search and counters. */
function toast(t){el.toast.textContent=t;el.toast.classList.add('show');setTimeout(()=>el.toast.classList.remove('show'),1500)}
function renderNav(){let meta=catalogMeta().filter(metaAvailable).filter(s=>state.pack==='all'||packOf(s)===state.pack);el.nav.innerHTML=`<button class="side-link ${state.cat==='all'&&state.mode==='library'?'active':''}" data-cat="all"><span>⌂</span><b>كل العناصر</b><em>${meta.length}</em></button>`+categories.map(cat=>`<button class="side-link ${state.cat===cat.id&&state.mode==='library'?'active':''}" data-cat="${cat.id}"><span>${cat.icon}</span><b>${cat.ar}</b><em>${meta.filter(s=>s.category===cat.id).length}</em></button>`).join('')}
function renderOverview(){let scoped=samples.filter(s=>available(s)&&(state.pack==='all'||packOf(s)===state.pack)),list=categories.filter(cat=>scoped.some(s=>s.category===cat.id)).sort((a,b)=>catUse(b.id)-catUse(a.id)).slice(0,10),max=Math.max(1,...list.map(cat=>catUse(cat.id)));el.catGrid.innerHTML=list.map((cat,i)=>`<button class="category-card" data-cat="${cat.id}"><span class="rank">${String(i+1).padStart(2,'0')}</span><span class="cat-icon">${cat.icon}</span><strong>${cat.ar}</strong><small>${cat.en} · ${scoped.filter(s=>s.category===cat.id).length} نماذج</small><div class="meter"><span style="width:${Math.max(7,catUse(cat.id)/max*100)}%"></span></div></button>`).join('')}
function renderFilters(){let cat=categories.find(x=>x.id===state.cat),styles=cat?cat.styles:['All','Minimal','Glass','Dark','Animated','Dashboard','Hover'],base=samples.filter(s=>available(s)&&(state.pack==='all'||packOf(s)===state.pack)&&(state.cat==='all'||s.category===state.cat)),tagCounts={};base.forEach(s=>(s.tags||[]).forEach(t=>tagCounts[norm(t)]=(tagCounts[norm(t)]||0)+1));let topTags=Object.entries(tagCounts).sort((a,b)=>b[1]-a[1]).slice(0,6).map(([t])=>t);let styleButtons=styles.map(s=>`<button class="filter ${state.filter===s?'active':''}" data-filter="${s}">${s==='All'?'الكل':s}</button>`).join('');let levels=[['basic','سهل'],['intermediate','متوسط'],['advanced','متقدم']].map(([k,l])=>`<button class="filter complexity ${state.filter==='complexity:'+k?'active':''}" data-filter="complexity:${k}">${l}</button>`).join('');let smart=[['special:new','الجديد'],['special:loop','Loop'],['special:interaction','Interactive'],['sort:used','الأكثر استخدامًا']].map(([k,l])=>`<button class="filter smart ${state.filter===k?'active':''}" data-filter="${k}">${l}</button>`).join('');let tags=topTags.map(t=>`<button class="filter tag-filter ${state.filter==='tag:'+t?'active':''}" data-filter="tag:${t}">#${t}</button>`).join('');el.filters.innerHTML=styleButtons+'<span class="filter-sep"></span>'+levels+'<span class="filter-sep"></span>'+smart+(tags?'<span class="filter-sep"></span>'+tags:'')}
function header(){let cat=categories.find(x=>x.id===state.cat),availableCount=catalogMeta().filter(metaAvailable).length,modeTitle={favorites:'المفضلة',recent:'آخر استخدام',trash:'سلة المحذوفات',collections:'المجموعات'}[state.mode];el.title.textContent=modeTitle||(state.q?`نتائج البحث عن: ${state.q}`:cat?cat.ar:'كل النماذج');el.eyebrow.textContent=state.mode==='trash'?'Trash':state.mode==='collections'?'Collections':state.mode!=='library'?'مساحتي':cat?cat.en:'المكتبة الكاملة';$('#componentTotal').textContent=availableCount;$('#categoryTotal').textContent=categories.length;$('#usageTotal').textContent=Object.values(state.usage).reduce((a,n)=>a+Number(n),0);$('#favCount').textContent=[...state.favorites].filter(id=>{let s=samples.find(x=>x.id===id);return s&&available(s)}).length;$('#recentCount').textContent=state.recent.filter(id=>{let s=samples.find(x=>x.id===id);return s&&available(s)}).length;$('#collectionCount').textContent=Object.keys(state.collections).length+5;$('#trashCount').textContent=state.trash.size;$('#clearSearch').hidden=!state.q;syncPackFilter()}
function renderAll(){resetGridWindow();renderNav();renderOverview();renderFilters();renderGrid();header();syncPackFilter()}
function renderInitial(){
  const started=performance.now();
  resetGridWindow();renderNav();header();syncPackFilter();
  requestAnimationFrame(()=>{
    renderOverview();renderFilters();renderGrid();
    requestAnimationFrame(()=>globalThis.LibraryPerformance?.recordRender?.('startup',performance.now()-started,document.querySelectorAll('.component-card').length));
  });

  const hydrateUniqueCatalog=async()=>{
    try{
      await globalThis.LibraryRegistry?.loadPack?.('all');
      resetGridWindow();renderNav();renderOverview();renderFilters();renderGrid();header();syncPackFilter();
      dispatchEvent(new CustomEvent('library:visual-dedupe-complete',{detail:globalThis.LibraryRegistry?.dedupeReport?.()}));
    }catch(err){console.warn('Visual dedupe hydration failed',err)}
  };
  if('requestIdleCallback' in window)requestIdleCallback(hydrateUniqueCatalog,{timeout:900});
  else setTimeout(hydrateUniqueCatalog,120);
}
function setCat(id){state.mode='library';state.cat=id;state.filter='All';state.q='';el.search.value='';$$('[data-view]').forEach(b=>b.classList.remove('active'));renderAll();$('#library').scrollIntoView({behavior:'smooth'});$('#sidebar').classList.remove('open')}
function recent(id){state.recent=[id,...state.recent.filter(x=>x!==id)].slice(0,12);persist();header()}
function mark(id){state.usage[id]=Number(state.usage[id]||0)+1;recent(id);persist();renderOverview();renderGrid();header()}
function toggleFav(id){state.favorites.has(id)?state.favorites.delete(id):state.favorites.add(id);persist();renderGrid();header();if(state.active?.id===id)el.fav.textContent=state.favorites.has(id)?'♥':'♡';toast(state.favorites.has(id)?'تمت الإضافة للمفضلة':'تمت الإزالة من المفضلة')}

function showView(v){if(v==='collections'){showCollectionPreset('dashboard');return}state.mode=v;state.cat='all';state.pack='all';state.q='';state.filter='All';resetGridWindow();el.search.value='';let list=[];if(v==='favorites')list=[...state.favorites].map(id=>samples.find(s=>s.id===id)).filter(s=>s&&available(s));else if(v==='recent')list=state.recent.map(id=>samples.find(s=>s.id===id)).filter(s=>s&&available(s));else if(v==='trash')list=[...state.trash].map(id=>samples.find(s=>s.id===id)).filter(s=>s&&!state.purged.has(s.id));renderNav();renderFilters();$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v));el.title.textContent=v==='favorites'?'المفضلة':v==='recent'?'آخر استخدام':'سلة المحذوفات';el.eyebrow.textContent=v==='trash'?'Trash':'مساحتي';renderGrid(list);header();$('#library').scrollIntoView({behavior:'smooth'});$('#sidebar').classList.remove('open')}
